
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T06:52:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a416730404f83caeaf9250b1aff24eadd53079c",
 "version": "0.23a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
