
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T08:28:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbe10721c36e56d672b1a2c0fdcd24d0dbe6176b",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
