
thingsboard:
  host: smartapp.netcad.com
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: true
    statsSendPeriodInSeconds: 3600
    configuration: statistics.json
  minPackSendDelayMS: 0
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: NQCeki9pGA2mUNKtIXJ6
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
-
  name: Custom MQTT Connector
  type: mqtt
  configuration: mqtt_custom.json
  class: CustomMqttUplinkConverter
  hostIP: broker.hivemq.com
  clientID: DEVICE-rtu1
  user: user
  pass: password
-
  name: Custom MQTT Connector
  type: mqtt
  configuration: mqtt_custom.json
  class: CustomMqttUplinkConverter
  hostIP: broker.hivemq.com
  clientID: DEVICE-rtu2
  user: user
  pass: password
