
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T16:56:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "effe50633a02e6da3626bbded9e1b0e49e0dad29",
 "version": "0.9.53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
