[project]
name = "DragAndDropTk"
version = "0.1.3"
authors = [
  { name="Lucas Rocha", email="lucash.rocha@hotmail.com" },
]
description = "A generic drag and drop widget to Tkinter applications"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"