[tool.poetry]
name = "aliby"
version = "0.1.34"
description = "Process and analyse live-cell imaging data"
authors = ["Alan Munoz <alan.munoz@ed.ac.uk>"]
packages = [
    { include = "aliby" },
    { include = "extraction" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "1.21.6" # Pinning numpy and pandas makes dep resolution much faster
pandas = "1.3.3"
dask = "^2021.12.0"
pathos = "^0.2.8"
tqdm = "^4.62.3"
scikit-learn = "0.22.2.post1"
py-find-1st = "^1.1.5"
scikit-image = ">=0.18.1"
opencv-python = "*"
requests-toolbelt = "^0.9.1"
h5py = "2.10" # I/O into files
imageio = "2.8.0"
omero-py = ">=5.6.2" # contact omero server
aliby-agora = "^0.2.30"
aliby-baby = "^0.1.13"
aliby-post = "^0.1.30"
p-tqdm = "^1.3.3" # Parallel progress bars
xmltodict = "^0.13.0" # read ome-tiff metadata
zeroc-ice = {version="3.6.5"} # networking interface, slow to build
# zeroc-ice = {version="3.6.5", optional=true} # To be set as optional in the future


[tool.poetry.dev-dependencies]
black = "^22.3.0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"
numpydoc = "^1.3.1"
pyflakes = "^2.4.0"
isort = "^5.10.1"
jupyter = "^1.0.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
[tool.isort]
multi_line_output = 3
line_length = 79
include_trailing_comma = true

