[tool.poetry]
name = "wj_analysis"
version = "0.8.1"
description = "Whale&Jaguar Libary - Analysis"
authors = ["Sebastian Franco <jsfranco@whaleandjaguar.co>"]
license = "GNU3"

[tool.poetry.dependencies]
python = ">3.7.1,<4.0"
pandas = "^1.3.2"
numpy = "1.21.0"
scikit-learn = "^1.0.2"
nltk = "^3.7"
spacy = "^3.2.2"

[tool.poetry.dev-dependencies]
gitlint = "^0.15.1"
flake8 = "^3.9.2"
flake8-bugbear = "^21.9.1"
black = "^21.9b0"
nox = "^2021.6.12"
isort = "^5.9.3"
autoflake = "^1.4"
flake8-gl-codeclimate = "^0.1.4"
python-semantic-release = "^7.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = 'app/.venv/*'

[tool.isort]
profile = "black"

[tool.semantic_release]
version_variable = [
  "__init__.py:__version__",
  "pyproject.toml:version"
]
version_source = "tag"
commit_version_number = false

branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "poetry build"