[project]
name = "groll"
version = "0.0.1"

requires-python = ">=3.10"
dependencies = ["click >= 8.1.3"]

[project.scripts]
groll = "groll.groll:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
