[tool.poetry]
name = "monadiacpy"
version = "0.1.0"
description = ""
authors = ["CaMMelo <cmelo.marcelo.pereira@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
atomicwrites = "^1.4.1"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"