[tool.poetry]
name = "neurips_cellseg_gc"
version = "0.0.4"
description = ""
authors = ["Cheng Ge"]
license = "MIT"

[tool.poetry.dependencies]
monai = "0.9"
numpy = "1.21.2"
nibabel = "3.2.1"
scikit-image = "0.19.2"
pillow = "9.0.1"
tensorboard = "2.8.0"
gdown = "4.2.0"
torchvision = "0.11.2"
tqdm = "4.63.0"
psutil = "5.8.0"
pandas = "1.4.1"
einops = "0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pre_process_3class = "neurips_cellseg_gc.data.pre_process_3class:main"
model_training_3class = "neurips_cellseg_gc.model_training_3class:main"
predice = "neurips_cellseg_gc.predict:main"
