[project]
name = "kismet"
version = "0.9.0"
authors = [{ name = "Mara Kim", email = "mara@autochthe.net" }]
description = "The conversational randomness generator"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]
dependencies = [
	"aiohttp",
	"discord.py",
	"ipython>=7",
	"jupyterlab",
	"lark-parser",
	"numpy",
	"prompt_toolkit",
	"slackclient",
	"torch",
]

[project.optional-dependencies]
dev = ["bumpversion", "pytest-runner>=2.0", "pytest", "twine"]


[project.urls]
"Homepage" = "https://github.com/autochthe/kismet-py"
"Bug Tracker" = "https://github.com/autochthe/kismet-py"

[build-system]
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"
