# flake8: noqa

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.15.0"

# import ApiClient
from kdp_api.api_client import ApiClient

# import Configuration
from kdp_api.configuration import Configuration

# import exceptions
from kdp_api.exceptions import OpenApiException
from kdp_api.exceptions import ApiAttributeError
from kdp_api.exceptions import ApiTypeError
from kdp_api.exceptions import ApiValueError
from kdp_api.exceptions import ApiKeyError
from kdp_api.exceptions import ApiException
