name: MacOS
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: excitedleigh/setup-nox@v2.1.0
      - name: run tests
        run: |
          nox -s test-data-download-source
          nox -s test-data-download-generated-ci
          nox -s coverage -- fix-prep-csv-paths running-on-ci
