
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T20:59:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "48a99b18d8df9333388ca82d10e9561357367b09",
 "version": "v1.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
