
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T16:22:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8622ff1f85a3f4b7ffd1877f063cc0963ec302c2",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
