CREATE TABLE "prod2-generico"."cfr-patient-request" (
	"short-book-id" float8 NOT NULL,
	"store-id" int4 NOT NULL,
	"store-name" varchar(255) NULL,
	"shortbook-date" date NULL,
	"patient-id" int4 NOT NULL,
	"unique-id" int8 NOT NULL,
	"drug-id" int4 NULL,
	"drug-name-x" varchar(255) NULL,
	composition varchar(1000) NULL,
	"repeatability-index" int4 NULL,
	"drug-category" varchar(255) NULL,
	"drug-type" varchar(255) NULL,
	"requested-quantity" int4 NULL,
	"inventory-at-creation" float8 NULL,
	"home-delivery" int4 NULL,
	"drug-name-y" varchar(255) NULL,
	"created-at" timestamp NULL,
	"received-at" timestamp NULL,
	"fulfilment-hours" float8 NULL,
	"bill-id" int4 NULL,
	"bill-date" date NULL,
	"within-tat-flag" int4 NULL,
	"within-tat-sold-quantity" numeric(10, 4) NULL,
	"loss-quantity" numeric(10, 4) NULL,
	"system-present" int4 NULL,
	"attributed-rate" numeric(10, 4) NULL,
	"final-lost-sales" numeric(10, 4) NULL,
	"attributed-loss-date" date NULL,
	"num-days-sold" int4 NULL,
	"last-sold" date NULL,
	min float8 NULL,
	"safe-stock" float8 NULL,
	max float8 NULL,
	"drug-grade" varchar(255) NULL,
	"loss-tag" varchar(255) NULL,
	"etl-created-at" timestamp NULL,
	"etl-created-by" varchar(255) NULL,
	"etl-updated-at" timestamp NULL,
	"etl-updated-by" varchar(255) NULL
);

CREATE TABLE "prod2-generico"."crm-conversion-overall" (
	"patient-id" int4 NULL,
	"store-id" int4 NULL,
	"call-date" date NULL,
	"bill-date" date NULL,
	spend float4 NULL,
	connected int4 NULL,
	"created-at" timestamp NULL,
	"created-by" varchar(255) NULL,
	"updated-at" timestamp NULL,
	"updated-by" varchar(255) NULL
);