
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T08:58:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "504c75793d9057ecc05b5990450d411ffc0e05d0",
 "version": "1.0.3.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
