[tool.poetry]
name = "chilitools"
version = "0.1.56"
description = "A collection of tools for working with the CHILI publish REST API"
authors = ["Austin <austin.meier@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
coloredlogs = "^15.0.1"
xmltodict = "^0.12.0"
pyperclip = "^1.8.2"
img2pdf = { version = "^0.4.4", optional = true }
Pillow = { version = "^9.1.0", optional = true }

[tool.poetry.extras]
images = [
  "img2pdf",
  "Pillow"
]

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
