[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pybasicdtw"
version = "0.0.4"
authors = [
  { name="Nikhil Reji", email="nikhil.reji@live.co.uk" },
]
description = "A readable dynamic time warping library."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/UomoCaffeLatte/PyBasicDTW"