
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T09:26:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4efe66e5045384c1f03f9b3ded5cb80c6e3045c",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
