
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T16:40:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b9ce0e69a9297ab04217b49cb6e7126fa473cd7",
 "version": "2693"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
