
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T18:19:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4912d9741d1949351ea5dff4eb1afb574f02a51",
 "version": "2.7.6.dev20220712"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
