
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-10T02:49:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b287dfc6a7c397523ba67e10a0436099fb0a44f7",
 "version": "0.10.dev2228"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
