
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T13:50:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b9152f823de15cfb89ca026adbe1655eb2e1008",
 "version": "0.23a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
