
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T15:45:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "14ecb5dd07e3098bd3d204f040347656a1a32c87",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
