name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Define job steps
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install system build deps
        run: sudo apt-get update -y && sudo apt-get install -y --no-install-recommends build-essential gcc libsndfile1

      - name: Install build dependencies
        run: pip install -e .[build]

      - name: Install test dependencies
        run: pip install -e .[test]

      - name: Install local dependencies on editable mode
        run: pip install -e .

      - name: Test using pytest
        run: pytest tests/ --cov=mixsim --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml # coverage report
          token: ${{ secrets.CODECOV_TOKEN }} # Just for test
          verbose: true