VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('07')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 0
MINOR_VERSION = 6
PATCH_VERSION = 202207070816
version_date = '2022/07/07 08:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
