[tool.poetry]
name = "dbnomics-data-model"
version = "0.13.29"
description = "Provide classes for DBnomics entities and a storage abstraction"
authors = ["DBnomics Team <contact@nomics.world>"]
license = "AGPLv3+"
readme = "README.md"
repository = "https://git.nomics.world/dbnomics/dbnomics-data-model"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
daiquiri = "^3.0.1"
dirsync = "^2.2.5"
jsonschema = "^4.4.0"
orjson = "^3.6.7"
pydantic = "^1.9.0"
pysimdjson = "^4.0.3"
python-dateutil = "^2.8.2"
toolz = "^0.11.2"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
dlint = "^0.12.0"
flake8 = "^4.0.1"
flake8-blind-except = "^0.2.1"
flake8-breakpoint = "^1.1.0"
flake8-bugbear = "^22.3.23"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.8.0"
flake8-docstrings = "^1.6.0"
flake8-eradicate = "^1.2.0"
flake8-fixme = "^1.1.1"
flake8-logging-format = "^0.6.0"
flake8-mutable = "^1.2.0"
flake8-print = "^4.0.0"
flake8-rst-docstrings = "^0.2.5"
isort = "^5.10.1"
mypy = "^0.942"
pep8-naming = "^0.12.1"
pytest = "^7.1.1"
types-python-dateutil = "^2.8.10"
flake8-implicit-str-concat = "^0.3.0"

[tool.poetry.scripts]
dbnomics-update-storage = "dbnomics_data_model.scripts.update_storage:app"
dbnomics-validate-storage = "dbnomics_data_model.scripts.validate_storage:app"

[tool.black]
line-length = 120

# From https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort
[tool.isort]
line_length = 120
profile = "black"
src_paths = ["dbnomics_data_model", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
