
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T17:21:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d7a2fd315e11109d83011fad263eb0f7c36586a",
 "version": "0.2.12.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
