
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T03:27:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "784cf30cf610f7bc9f7ee9af0a0a61ffcc448c35",
 "version": "1.17.0.post.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
