[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "id_manual_tools"
version = "0.0.2"
authors = [
  { name="Jordi Torrents", email="jordi.torrentsm@gmail.com" },
]
description = "Tools for using idtracker.ai"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# [project.urls]
# "Homepage" = "not_yet"
# "Bug Tracker" = "not_yet"


[project.scripts]
hello-world = "id_manual_tools.manual_tracking:test"
