
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T07:45:44-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "7013aa9dbbcd67658c6bb83d32b9e83c4d43216c",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
