[tool.poetry]
name = "common"
version = "0.0.26"
description = ""
authors = ["Your Name <you@example.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = ">=0.19.1"
aioredis = "^2.0.1"
python-json-logger = ">=0.1.11<=2.0.2"
aioboto3 = "^9.6.0"
xmltodict = "^0.13.0"
minio = "^7.1.8"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
testcontainers = "3.4.2"
coverage = "5.3"
faker = "9.8.0"
pytest-env = "0.6.2"
python-dotenv = "0.19.1"
redis = "^4.3.1"
pytest-httpx = "^0.21.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
