[tool.poetry]
name = "prefield"
version = "0.1.8"
description = "Prefect tasks and CLI functionality to be used across Prefect projects"
authors = [
    "atsangarides <andreas@field.energy>",
    "Tomme <tom@field.energy>"
]


[tool.poetry.dependencies]
python = "^3.8"
prefect = "^0.15.13"


[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = "^21.9b0"
pre-commit = "^2.15.0"
numpy = {version = "1.21.5", python = "3.8.12"}
pandas = "1.3.5"
pyarrow = "^6.0.0"
boto3 = "^1.21.1"
python-dotenv = "^0.19.2"
mypy = "^0.931"
boto3-stubs = {extras = ["essential"], version = "^1.21.6"}
types-pytz = "^2021.3.5"
types-python-dateutil = "^2.8.9"

[tool.poetry.scripts]
prefield = "prefield.cli.main:main"

[tool.mypy]
plugins = [
    # "pydantic.mypy" example plugin
]

[[tool.mypy.overrides]]
module = [
    "docker",
    "pandas"
]

ignore_missing_imports = true
[tool.black]
line-length = 89
target-version = ['py38']
exclude = '''
(
    asv_bench/env
  | \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)
'''

[tool.pytest.ini_options]
# sync minversion with pyproject.toml & install.rst
log_cli = false
log_level = "WARNING"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
doctest_optionflags = [
  "NORMALIZE_WHITESPACE",
  "IGNORE_EXCEPTION_DETAIL",
  "ELLIPSIS",
]

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true
line_length = 89

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
