[tool.poetry]
name = "tidy3d-model"
version = "0.1.2"
description = ""
authors = ["An Li <kidylee@gmail.com>"]
packages = [
    {include = "tidy3d"}
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
