
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T14:40:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8a05f291861a8bd3ba0ac47b724d431c48bdfe5",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
