[tool.poetry]
name = "sapiadapter"
version = "0.31.402561"
description = ""
authors = ["Zafar Iqbal <zaf@sparc.space>"]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
