[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thetadata"
version = "0.0.1"
authors = [
  { name="Adler Weber", email="adlerweber8430@gmail.com" },
  { name="Bailey Danseglio", email="baileydan911@gmail.com" },
]
description = "Python API for ThetaData"
homepage = "https://thetadata.net"
repository = "https://github.com/ThetaData-API/PythonAPI"
documentation = "https://TODO.com"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "tqdm",
  "pandas"
]

[project.optional-dependencies]
tests = [
  "coverage>=5.0.3",
  "pytest",
  "pytest-benchmark[histogram]>=3.2.1",
]
docs = [
    "mkdocs",
    "mkdocstrings[python]"
]

[project.urls]
"Bug Tracker" = "https://github.com/ThetaData-API/PythonAPI/issues"
