
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-07-11T14:55:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "07eaf1a9cf1c68f66354ce1e8e009f1bd6d3644b",
 "version": "2.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
