[tool.poetry]
name = "globus_action_provider_tools_fastapi"
version = "0.1.0a2"
description = ""
authors = ["Jim Pruyne <pruyne@uchicago.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.78"
arrow = "^1"
globus-action-provider-tools = "^0.12.0"

[tool.poetry.dev-dependencies]
importmagic = "^0.1.7"
epc = "^0.0.5"
pytest-asyncio = "^0.18.2"
pre-commit = "^2.17.0"
sqlmodel = "^0.0.6"
python-lsp-server = "^1"
pyls-flake8 = "^0"
pylsp-mypy = "^0"
pyls-isort = "^0"
python-lsp-black = "^1"
pylsp-rope = "^0"
boto3 = "^1"
boto3-stubs = {extras = ["essential"], version = "^1"}

[tool.isort]
profile = "black"
src_paths = ["globus_action_provider_tools_fastapi"]

[tool.mypy]
python_version = 3.8
platform = "linux"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
