
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T18:27:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e5f776b41c17dcc63e6cf9b70dd239e381fb005",
 "version": "2.9.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
