VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('09')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202207091216
version_date = '2022/07/09 12:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
