[tool.poetry]
name = "pinnwand"
version = "1.3.2"
description = "Straightforward pastebin software."
authors = ["supakeen <cmdr@supakeen.com>"]
license = "MIT"
readme = "README.rst"
keywords = ["pastebin"]
repository = "https://github.com/supakeen/pinnwand"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
tornado = "^6.1"
pygments = "^2.4"
sqlalchemy = "^1.4"
click = "^8.0"
docutils = "^0.17"
toml = "^0.10.0"
pygments-better-html = "^0.1.0"
token-bucket = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
coverage = "^6.3"
black = { version = "*", allow-prereleases = true }
pytest-cov = "^3.0"
pre-commit = "^1.20"
flake8 = "^4.0"
mypy = "^0.931.0"

[tool.black]
line-length = 80
target_version = ["py36"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.poetry.scripts]
pinnwand = 'pinnwand.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
