
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T16:17:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ec1ca43c825e07362438268d43e85d4668b9e25",
 "version": "0.2.12.post0.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
