
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T10:48:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7207d5b0406ec4fc1e01dd3b818e22b1bb94f1f0",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
