
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T14:48:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bce1a74aca0bfbf79a481e7066c9e934455edf4",
 "version": "v1.0.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
