[tool.poetry]
name = "mainframe"
version = "0.0.3"
description = "Central Repo for datasets"
authors = ["chrisaddy <chris.william.addy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pydantic = "^1.9.1"
numpyro = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tox = "^3.25.1"
jupyterlab = "^3.4.3"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
