[tool.poetry]
name = "speedpycom"
version = "0.1.15"
description = "The Django Framework for SaaS"
authors = ["Kostja P <123@appliku.com>"]
readme = 'README.md'
repository = 'https://gitlab.com/speedpycom/speedpycom'
[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.6"
Pillow = "^9.2.0"
gunicorn = "^20.1.0"
whitenoise = "^6.2.0"
sentry-sdk = "^1.6.0"
requests = "^2.28.1"
celery = "^5.2.7"
psycopg2-binary = "^2.9.3"
arrow = "^1.2.2"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "^5.2.0"
django-configurations = "^2.3.2"
django-storages = "^1.12.3"
django-cors-headers = "^3.13.0"
django-braces = "^1.15.0"
django-extensions = "^3.1.5"
django-post-office = "^3.6.0"
django-crispy-forms = "^1.14.0"
django-allauth = "^0.51.0"
boto3 = "^1.24.26"
boto3-stubs = "^1.24.26"
django-import-export = "^2.8.0"
honeybadger = "^0.8.0"
django-ckeditor = "^6.4.2"
drf-spectacular = "^0.22.1"
django-tailwind = "^3.3.0"
dj-database-url = "^0.5.0"
django-cache-url = "^3.4.2"
flower = "^1.1.0"
celery-redbeat = "^2.0.0"
djangoql = "^0.17.1"
django-redis = "^5.2.0"
django-ses = "^3.1.0"
wagtail = "^3.0.1"
wagtailcodeblock = "^1.28.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
