[tool.poetry]
name = "envawareconfig"
version = "0.2.1"
description = "Load configurations from yaml files with automatic environment variable substitution"
authors = ["marcello <marcello.frattini7@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mfrattini7/envawareconfig"


[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
