[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "hex-color-terminal"
version = "0.0.3"
authors = [
  { name="Cownex", email="contact@cownex.de" },
]
description = "Print Colored Text with Hexcodes!"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Cownex/HexOutput"
"Bug Tracker" = "https://github.com/Cownex/HexOutput/issues/"