
[tool.check-manifest]
ignore = [".travis.yml",
          "docs/_function_autosummary/*"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "23.27.0"
tag_format = "v$version"
version_files = ["VERSION"]
update_changelog_on_bump = true

[tool.isort]
profile = 'black'

[tool.black]
extend-exclude = 'ldas.py'
