[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pingline"
version = "0.0.7"
authors = [
  { name="Ilia Peterov", email="ipeterov1@gmail.com" },
]
description = "A small tool for pinging multiple hosts at once and exploring the data"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]
dependencies = [
    "matplotlib==3.5.2",
    "pandas==1.4.3",
    "click==8.1.3",
]


[project.urls]
"Homepage" = "https://github.com/ipeterov/pingline"
"Bug Tracker" = "https://github.com/ipeterov/pingline/issues"

[project.scripts]
pingline = "src.cli:cli"