[tool.poetry]
name = "cognite-seismic-sdk"
version = "0.2.103"
description = ""
authors = ["cognite <support@cognite.com>"]

packages = [
    { include="cognite" },
]
include = ["cognite/seismic/protos/**/*.py"]

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'
exclude = '(cognite/seismic/protos/*|\.tox/*)'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '*cognite/seismic/protos*'    # this makes sort all Python files
known_third_party = ["cognite", "google", "grpc", "numpy", "pytest"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py38

[testenv]
deps =
    pytest
    pytest-mock
    pytest-cov
commands =
    coverage run -m pytest -v tests
    coverage xml
extras =
    tox_deps
passenv = COGNITE_API_KEY COGNITE_API_HOST COGNITE_PROJECT AZUREAD_PRIVATE_KEY
"""

[tool.poetry.dependencies]
deprecation = "^2.1.0"
grpcio= "^1.31"
grpcio-tools = "^1.31"
numpy = "^1.17"
oauthlib = "^3.1.1"
python = "^3.6.1"
python-dateutil = "^2.8"
protobuf = "^3.15.0"
requests = "^2.26.0"
requests_oauthlib = "^1.3.0"
six = "^1.14"
urllib3 = "^1.24"

# Extras, because tox ignores dev dependencies.
msal = {version = "^1.15.0", optional = true}
shapely = {version = "^1.7", optional = true}

[tool.poetry.dev-dependencies]
black = "=19.3b0"
isort = "^5.9"
nbsphinx = "^0.8.2"
pytest = "^5.2"
pytest-mock = "^3.5"
pytest-cov = "^2.8"
sphinx = "^2.2"
pre-commit = "^1.18"
tox = "^3.20"
sphinx-pypi-upload = "^0.2.1"
sphinx-rtd-theme = "^0.5"
# tox-pyenv disabled for now, since we only test against one python
# tox-pyenv = "^1.1"
seed-isort-config = "^1.9"
mypy = "^0.730.0"
flake8 = "^3.8"
pydantic = "^1.8.1"
recommonmark = "^0.7.1"
nbsphinx-link = "^1.3.0"
ipython = "7.10"
twine = "3.4.1"
certifi = ">= 2021.05.30"

[tool.poetry.extras]
tox_deps = ["msal", "shapely"]

[[tool.poetry.source]]
name = "snakepit"
url = "https://cognite.jfrog.io/cognite/api/pypi/snakepit/simple"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
