VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('13')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('18')
MAJOR_VERSION = 2
MINOR_VERSION = 19
PATCH_VERSION = 202207130518
version_date = '2022/07/13 05:18'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
