# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/memory/memory_case.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/memory/memory_case.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%oneflow/core/memory/memory_case.proto\x12\x07oneflow\"%\n\x10\x43udaPinnedMemory\x12\x11\n\tdevice_id\x18\x01 \x02(\x03\"@\n\nHostMemory\x12\x32\n\x0f\x63uda_pinned_mem\x18\x01 \x01(\x0b\x32\x19.oneflow.CudaPinnedMemory\"%\n\x10\x44\x65viceCudaMemory\x12\x11\n\tdevice_id\x18\x01 \x02(\x03\"s\n\nMemoryCase\x12\'\n\x08host_mem\x18\x01 \x01(\x0b\x32\x13.oneflow.HostMemoryH\x00\x12\x34\n\x0f\x64\x65vice_cuda_mem\x18\x02 \x01(\x0b\x32\x19.oneflow.DeviceCudaMemoryH\x00\x42\x06\n\x04\x63\x61se')
)




_CUDAPINNEDMEMORY = _descriptor.Descriptor(
  name='CudaPinnedMemory',
  full_name='oneflow.CudaPinnedMemory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='oneflow.CudaPinnedMemory.device_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=87,
)


_HOSTMEMORY = _descriptor.Descriptor(
  name='HostMemory',
  full_name='oneflow.HostMemory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cuda_pinned_mem', full_name='oneflow.HostMemory.cuda_pinned_mem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=153,
)


_DEVICECUDAMEMORY = _descriptor.Descriptor(
  name='DeviceCudaMemory',
  full_name='oneflow.DeviceCudaMemory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='oneflow.DeviceCudaMemory.device_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=192,
)


_MEMORYCASE = _descriptor.Descriptor(
  name='MemoryCase',
  full_name='oneflow.MemoryCase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_mem', full_name='oneflow.MemoryCase.host_mem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_cuda_mem', full_name='oneflow.MemoryCase.device_cuda_mem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='case', full_name='oneflow.MemoryCase.case',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=194,
  serialized_end=309,
)

_HOSTMEMORY.fields_by_name['cuda_pinned_mem'].message_type = _CUDAPINNEDMEMORY
_MEMORYCASE.fields_by_name['host_mem'].message_type = _HOSTMEMORY
_MEMORYCASE.fields_by_name['device_cuda_mem'].message_type = _DEVICECUDAMEMORY
_MEMORYCASE.oneofs_by_name['case'].fields.append(
  _MEMORYCASE.fields_by_name['host_mem'])
_MEMORYCASE.fields_by_name['host_mem'].containing_oneof = _MEMORYCASE.oneofs_by_name['case']
_MEMORYCASE.oneofs_by_name['case'].fields.append(
  _MEMORYCASE.fields_by_name['device_cuda_mem'])
_MEMORYCASE.fields_by_name['device_cuda_mem'].containing_oneof = _MEMORYCASE.oneofs_by_name['case']
DESCRIPTOR.message_types_by_name['CudaPinnedMemory'] = _CUDAPINNEDMEMORY
DESCRIPTOR.message_types_by_name['HostMemory'] = _HOSTMEMORY
DESCRIPTOR.message_types_by_name['DeviceCudaMemory'] = _DEVICECUDAMEMORY
DESCRIPTOR.message_types_by_name['MemoryCase'] = _MEMORYCASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CudaPinnedMemory = _reflection.GeneratedProtocolMessageType('CudaPinnedMemory', (_message.Message,), {
  'DESCRIPTOR' : _CUDAPINNEDMEMORY,
  '__module__' : 'oneflow.core.memory.memory_case_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.CudaPinnedMemory)
  })
_sym_db.RegisterMessage(CudaPinnedMemory)

HostMemory = _reflection.GeneratedProtocolMessageType('HostMemory', (_message.Message,), {
  'DESCRIPTOR' : _HOSTMEMORY,
  '__module__' : 'oneflow.core.memory.memory_case_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.HostMemory)
  })
_sym_db.RegisterMessage(HostMemory)

DeviceCudaMemory = _reflection.GeneratedProtocolMessageType('DeviceCudaMemory', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECUDAMEMORY,
  '__module__' : 'oneflow.core.memory.memory_case_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.DeviceCudaMemory)
  })
_sym_db.RegisterMessage(DeviceCudaMemory)

MemoryCase = _reflection.GeneratedProtocolMessageType('MemoryCase', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYCASE,
  '__module__' : 'oneflow.core.memory.memory_case_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.MemoryCase)
  })
_sym_db.RegisterMessage(MemoryCase)


# @@protoc_insertion_point(module_scope)
