
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "52ec17b2aa5c4365d3301c01fcad360bffddc892",
 "version": "7.6.4pre3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
