{% set name = "vak" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 42780295bef28693980d02dc9a748b12c8672b1de3413506c05db6ed787cb5a7

build:
  number: 0
  entry_points:
    - vak=vak.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - attrs >=19.1.*
    - crowsetta ==1.1.1
    - dask >=2.1.*
    - dask-core >=2.1.*
    - joblib
    - matplotlib
    - numpy >=1.16
    - pip
    - python >=3.6.*
    - scipy
    - tensorflow =1.13
    - tensorflow-gpu =1.13
    - tqdm
  run:
    - attrs >=19.1.*
    - crowsetta ==1.1.1
    - dask >=2.1.*
    - dask-core >=2.1.*
    - joblib
    - matplotlib
    - numpy >=1.16
    - python >=3.6.*
    - scipy
    - tensorflow =1.13
    - tensorflow-gpu =1.13
    - tqdm

test:
  imports:
    - vak
    - vak.cli
    - vak.config
    - vak.core
    - vak.core.learncurve
    - vak.io
    - vak.io.dataset
    - vak.io.algorithms
    - vak.plot
    - vak.utils
  commands:
    - vak --help

about:
  home: "https://github.com/NickleDave/vak"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "automated annotation of vocalizations for everybody"
  doc_url: "https://vak.readthedocs.io"
  dev_url: 

extra:
  recipe-maintainers:
    - nickledave
