[project]
name = "dir_clean"
version = "0.1.3"
authors = [
  { name="DDGG", email="ddcatgg@gmail.com" },
]
description = "This package can help you to clean up the directory."
readme = "README.md"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ['run', 'tool']
requires-python = ">=2.7,>=3.6"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/ddcatgg/dir_clean"
"Bug Tracker" = "https://github.com/ddcatgg/dir_clean/issues"
