
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T17:08:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f99ada9d2845029cb24d3508c5260fa73aa6428f",
 "version": "4.7.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
