[tool.poetry]
name = "celery-gsheets"
version = "0.1.0"
description = "A celery package for gsheets"
authors = ["David Jeong <drumrobot@1do.space>"]

[tool.poetry.dependencies]
python = "^3.8"
celery = "^5.2.7"
pygsheets = "^2.0.5"
python-decouple = "^3.6"
redis = "^4.3.4"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pre-commit = "^2.19.0"
pytest = "^7.1.2"

[tool.poetry.urls]
"Homepage" = "https://github.com/ODCNC/celery-gsheets"
"Bug Tracker" = "https://github.com/ODCNC/celery-gsheets/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization=true
