
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T16:38:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7add7c5ff5698e04142e98129550077684d9b01",
 "version": "0.2.12.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
