
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T10:51:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "df3c7182e83295ba3ca8ec9d6eacbb1ff8444496",
 "version": "2691"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
