
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T16:05:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4e423b82bbf29c8a637fa06916f433270c26b21",
 "version": "0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
