[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcss-api"
version = "0.0.2"
authors = [
  { name="Les Packages", email="les.packages@gmail.com" },
]
description = "A library to easily access the MCSS api."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 2.7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Docs" = "https://coming.soon/"