[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "raver"
version = "3.0.1"
description = "Ratio package management tool."
authors = ["Ratio Innovations B.V. <info@ratio-case.nl>"]
license = "MIT"
documentation = "https://raver.ratio-case.nl"
readme = "README.rst"
repository = "https://gitlab.com/ratio-case/python/raver"
homepage = "https://gitlab.com/ratio-case/python/raver"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
semver = "^2.13.0"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
black = "*"
invoke = "*"
pydata-sphinx-theme = "*"
pytest = "*"
pytest-cov = "*"
pytest-doctestplus = "*"
Sphinx = { version = "*" }
sphinx-autoapi = { version = "*" }
sphinx-copybutton = { version = "*" }
sphinx-prompt = { version = "*" }
sphinxemoji = { version = "*" }

[tool.poetry.scripts]
raver = "raver.cli:cli"

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report xml:./.pytest_cache/coverage.xml --cov-report term-missing --doctest-plus --doctest-rst"
testpaths = ["docs", "tests"]

[tool.coverage.run]
source = [
    "raver",
    "/usr/local/lib/python3.9/site-packages/raver",
    "/home/ratio/.local/lib/python3.9/site-packages/raver",
]
disable_warnings = ["module-not-imported"]

[tool.coverage.paths]
source = [
    "raver",
    "/usr/local/lib/python3.9/site-packages/raver",
    "/home/ratio/.local/lib/python3.9/site-packages/raver",
]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.raver]
ref = "origin/master"
changelog = "./docs/source/changelog.rst"
