
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T16:13:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1050e73e15ef7b7de7e72cede04f7e92cf31f454",
 "version": "3.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
