INSERT_INTO_COLUMNS = "TRY_NUMBER,DAG_ID,RUN_ID,TASK_ID,EXEC_DATE,ELT_TS,LOG_TYPE,CATEGORY," \
                      "LOG_MESSAGE,DETAILED_MESSAGE,FILE_NAME,ELT_BY,SUB_TASK,SOURCE,APPLICATION"
MANIFEST_TABLE = "DAG_LOGS"
