[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "os_env_bob_ross"
version = "0.4"
authors = [
  { name="bob_ross", email="author@example.com" },
]
description = "a small dot env package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.2"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]