# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hoax"
version = "1.0.0"
description = "Hyperparemeter Optimzation Algorithms Explorer"
readme = "README.md"
authors = [{ name = "Albert Thie", email = "alb0rt@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["machine learning", "quantum chemistry", "optimzation"]
dependencies = [
    "torch",
    "numpy",
    'tomli; python_version < "3.11"',
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/AlbertThie/HOAX"

[project.scripts]
hoax = "hoax.__main__:main"
