
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T09:22:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e93a329ec8f50f14ce2d04d04b7618480ec6a1b3",
 "version": "2690"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
