[tool.poetry]
name = "mdsplit"
version = "0.2"
description = "Split markdown files at headings"
readme = "README.md"
authors = ["Markus Straub"]
license = "MIT"
repository = "https://github.com/markusstraub/mdsplit"

[tool.poetry.scripts]
mdsplit = "mdsplit:run"

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = ">=4"
pytest = ">=7"
ipykernel = ">=6.6"
pytest-console-scripts = ">=1.3.1"

[tool.pytest.ini_options]
addopts = ["-ra", "-W error"]

[tool.black]
line-length = 100
target-version = ['py310']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
