
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:00:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5411afc3180692bc332e9b4d0610500c6463e196",
 "version": "v1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
