
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T21:54:57+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "17e939ad54307ab70397488285af6cfc180817a8",
 "version": "0.2.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
