[tool.poetry]
name = "scrape-721"
version = "0.3.0"
description = "\"A basic tool for scraping ERC-721 smart contract data\""
authors = ["Corey Bothwell <corey.bothwell@uzh.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
scrape-721 = "scrape_721.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.4.2"
python-dotenv = "^0.20.0"
web3 = "^5.29.2"
redis = "^4.3.4"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
mypy = "^0.961"
pytest = "^5.2"
flake8 = "^4.0.1"
pylint = "^2.14.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Homepage" = "https://github.com/cmbothwell/scrape-721"