[tool.poetry.scripts]
soin = "soin.cli:cli"

[tool.poetry]
name = "soin"
version = "1.0.9"
description = "soin is a tool collections for spiders"
authors = ["chenglu <chenglu.she@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.1"
redis = "^4.3.4"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.2"
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
