[tool.poetry]
name = "pystrapi"
version = "4.5.0"
description = "Work with Strapi from Python via REST API"
authors = ["Noam Nol <noamnol19@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/NoamNol/py-strapi"
repository = "https://github.com/NoamNol/py-strapi"
keywords = ["strapi", "cms", "api", "rest"]
classifiers =[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
    ]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
aiohttp = "*"
requests = "^2.25.0"

[tool.poetry.dev-dependencies]
python-semantic-release = "*"
pydocstyle = "*"
toml = "*"
prospector = {version = "^1.7.7", extras = ["with_mypy", "with_bandit"]}
autopep8 = "^1.6.0"
pytest = "^7.1.2"
types-requests = "^2.27.30"
pytest-asyncio = "^0.18.3"
pydash = "^5.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
remove_dist = "false"
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
upload_to_release = "true"
upload_to_pypi = "true"
