# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['nonebot_ark_record', 'nonebot_ark_record.ark']

package_data = \
{'': ['*'],
 'nonebot_ark_record': ['.git/*',
                        '.git/hooks/*',
                        '.git/info/*',
                        '.git/logs/*',
                        '.git/logs/refs/heads/*',
                        '.git/objects/02/*',
                        '.git/objects/03/*',
                        '.git/objects/04/*',
                        '.git/objects/05/*',
                        '.git/objects/06/*',
                        '.git/objects/07/*',
                        '.git/objects/08/*',
                        '.git/objects/09/*',
                        '.git/objects/0d/*',
                        '.git/objects/0f/*',
                        '.git/objects/10/*',
                        '.git/objects/11/*',
                        '.git/objects/12/*',
                        '.git/objects/13/*',
                        '.git/objects/14/*',
                        '.git/objects/16/*',
                        '.git/objects/17/*',
                        '.git/objects/18/*',
                        '.git/objects/1a/*',
                        '.git/objects/1b/*',
                        '.git/objects/1c/*',
                        '.git/objects/1e/*',
                        '.git/objects/1f/*',
                        '.git/objects/20/*',
                        '.git/objects/22/*',
                        '.git/objects/23/*',
                        '.git/objects/24/*',
                        '.git/objects/25/*',
                        '.git/objects/26/*',
                        '.git/objects/28/*',
                        '.git/objects/29/*',
                        '.git/objects/2a/*',
                        '.git/objects/2b/*',
                        '.git/objects/2c/*',
                        '.git/objects/2d/*',
                        '.git/objects/2e/*',
                        '.git/objects/2f/*',
                        '.git/objects/32/*',
                        '.git/objects/33/*',
                        '.git/objects/34/*',
                        '.git/objects/35/*',
                        '.git/objects/36/*',
                        '.git/objects/37/*',
                        '.git/objects/38/*',
                        '.git/objects/3a/*',
                        '.git/objects/3f/*',
                        '.git/objects/46/*',
                        '.git/objects/48/*',
                        '.git/objects/49/*',
                        '.git/objects/4a/*',
                        '.git/objects/4c/*',
                        '.git/objects/4f/*',
                        '.git/objects/50/*',
                        '.git/objects/51/*',
                        '.git/objects/52/*',
                        '.git/objects/54/*',
                        '.git/objects/55/*',
                        '.git/objects/56/*',
                        '.git/objects/57/*',
                        '.git/objects/58/*',
                        '.git/objects/59/*',
                        '.git/objects/5a/*',
                        '.git/objects/5c/*',
                        '.git/objects/5d/*',
                        '.git/objects/5f/*',
                        '.git/objects/60/*',
                        '.git/objects/61/*',
                        '.git/objects/62/*',
                        '.git/objects/63/*',
                        '.git/objects/65/*',
                        '.git/objects/67/*',
                        '.git/objects/68/*',
                        '.git/objects/69/*',
                        '.git/objects/6a/*',
                        '.git/objects/6b/*',
                        '.git/objects/6c/*',
                        '.git/objects/6e/*',
                        '.git/objects/6f/*',
                        '.git/objects/71/*',
                        '.git/objects/72/*',
                        '.git/objects/76/*',
                        '.git/objects/78/*',
                        '.git/objects/79/*',
                        '.git/objects/7b/*',
                        '.git/objects/7c/*',
                        '.git/objects/7f/*',
                        '.git/objects/81/*',
                        '.git/objects/82/*',
                        '.git/objects/83/*',
                        '.git/objects/84/*',
                        '.git/objects/85/*',
                        '.git/objects/86/*',
                        '.git/objects/87/*',
                        '.git/objects/88/*',
                        '.git/objects/89/*',
                        '.git/objects/8b/*',
                        '.git/objects/8c/*',
                        '.git/objects/8e/*',
                        '.git/objects/8f/*',
                        '.git/objects/90/*',
                        '.git/objects/91/*',
                        '.git/objects/92/*',
                        '.git/objects/93/*',
                        '.git/objects/95/*',
                        '.git/objects/96/*',
                        '.git/objects/98/*',
                        '.git/objects/9a/*',
                        '.git/objects/9c/*',
                        '.git/objects/9e/*',
                        '.git/objects/9f/*',
                        '.git/objects/a0/*',
                        '.git/objects/a1/*',
                        '.git/objects/a2/*',
                        '.git/objects/a3/*',
                        '.git/objects/a5/*',
                        '.git/objects/a6/*',
                        '.git/objects/a7/*',
                        '.git/objects/a8/*',
                        '.git/objects/a9/*',
                        '.git/objects/aa/*',
                        '.git/objects/ab/*',
                        '.git/objects/ad/*',
                        '.git/objects/ae/*',
                        '.git/objects/b1/*',
                        '.git/objects/b3/*',
                        '.git/objects/b4/*',
                        '.git/objects/b5/*',
                        '.git/objects/b7/*',
                        '.git/objects/b8/*',
                        '.git/objects/b9/*',
                        '.git/objects/ba/*',
                        '.git/objects/bb/*',
                        '.git/objects/bd/*',
                        '.git/objects/be/*',
                        '.git/objects/bf/*',
                        '.git/objects/c0/*',
                        '.git/objects/c1/*',
                        '.git/objects/c2/*',
                        '.git/objects/c3/*',
                        '.git/objects/c4/*',
                        '.git/objects/c6/*',
                        '.git/objects/c9/*',
                        '.git/objects/cc/*',
                        '.git/objects/ce/*',
                        '.git/objects/cf/*',
                        '.git/objects/d1/*',
                        '.git/objects/d2/*',
                        '.git/objects/d3/*',
                        '.git/objects/d4/*',
                        '.git/objects/d7/*',
                        '.git/objects/d9/*',
                        '.git/objects/db/*',
                        '.git/objects/dd/*',
                        '.git/objects/de/*',
                        '.git/objects/df/*',
                        '.git/objects/e0/*',
                        '.git/objects/e1/*',
                        '.git/objects/e2/*',
                        '.git/objects/e3/*',
                        '.git/objects/e4/*',
                        '.git/objects/e5/*',
                        '.git/objects/e6/*',
                        '.git/objects/e7/*',
                        '.git/objects/ea/*',
                        '.git/objects/eb/*',
                        '.git/objects/ec/*',
                        '.git/objects/ed/*',
                        '.git/objects/ee/*',
                        '.git/objects/ef/*',
                        '.git/objects/f0/*',
                        '.git/objects/f1/*',
                        '.git/objects/f2/*',
                        '.git/objects/f5/*',
                        '.git/objects/f6/*',
                        '.git/objects/f7/*',
                        '.git/objects/f9/*',
                        '.git/objects/fa/*',
                        '.git/objects/fb/*',
                        '.git/objects/fd/*',
                        '.git/objects/fe/*',
                        '.git/refs/heads/*',
                        'res_file/record_image/*',
                        'resource/*',
                        'resource/profile/*',
                        'resource/ttf/*']}

install_requires = \
['Pillow', 'matplotlib', 'requests']

setup_kwargs = {
    'name': 'nonebot-ark-record',
    'version': '1.0.2',
    'description': 'Nonebot plugin for fetching and analyzing gacha records of arknights',
    'long_description': '📦 setup.py (for humans)\n=======================\n\nThis repo exists to provide [an example setup.py] file, that can be used\nto bootstrap your next Python project. It includes some advanced\npatterns and best practices for `setup.py`, as well as some\ncommented–out nice–to–haves.\n\nFor example, this `setup.py` provides a `$ python setup.py upload`\ncommand, which creates a *universal wheel* (and *sdist*) and uploads\nyour package to [PyPi] using [Twine], without the need for an annoying\n`setup.cfg` file. It also creates/uploads a new git tag, automatically.\n\nIn short, `setup.py` files can be daunting to approach, when first\nstarting out — even Guido has been heard saying, "everyone cargo cults\nthems". It\'s true — so, I want this repo to be the best place to\ncopy–paste from :)\n\n[Check out the example!][an example setup.py]\n\nInstallation\n-----\n\n```bash\ncd your_project\n\n# Download the setup.py file:\n#  download with wget\nwget https://raw.githubusercontent.com/navdeep-G/setup.py/master/setup.py -O setup.py\n\n#  download with curl\ncurl -O https://raw.githubusercontent.com/navdeep-G/setup.py/master/setup.py\n```\n\nTo Do\n-----\n\n-   Tests via `$ setup.py test` (if it\'s concise).\n\nPull requests are encouraged!\n\nMore Resources\n--------------\n\n-   [What is setup.py?] on Stack Overflow\n-   [Official Python Packaging User Guide](https://packaging.python.org)\n-   [The Hitchhiker\'s Guide to Packaging]\n-   [Cookiecutter template for a Python package]\n\nLicense\n-------\n\nThis is free and unencumbered software released into the public domain.\n\nAnyone is free to copy, modify, publish, use, compile, sell, or\ndistribute this software, either in source code form or as a compiled\nbinary, for any purpose, commercial or non-commercial, and by any means.\n\n  [an example setup.py]: https://github.com/navdeep-G/setup.py/blob/master/setup.py\n  [PyPi]: https://docs.python.org/3/distutils/packageindex.html\n  [Twine]: https://pypi.python.org/pypi/twine\n  [image]: https://farm1.staticflickr.com/628/33173824932_58add34581_k_d.jpg\n  [What is setup.py?]: https://stackoverflow.com/questions/1471994/what-is-setup-py\n  [The Hitchhiker\'s Guide to Packaging]: https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html\n  [Cookiecutter template for a Python package]: https://github.com/audreyr/cookiecutter-pypackage\n',
    'author': 'Kawataku',
    'author_email': None,
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/zheuziihau',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
