[tool.poetry]
name = "vectory"
version = "0.0.2"
description = "Streamline the benchmark and experimentation process of your models that rely on generating embeddings"
authors = ["Pento <hello@pento.ai>"]
readme = "README.md"
packages = [
    { include = "oss" }
]

[tool.poetry.scripts]
vectory = "oss.cli.main:app"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
elasticsearch = "7.16.3"
tqdm = "^4.61.1"
typer = "^0.4.0"
elasticsearch-dsl = ">=7.0.0,<8.0.0"
peewee = "^3.14.10"
numpy = ">=1.14.5,<=1.19.3"
pynndescent = "^0.5.6"
matplotlib = ">=3.3"

[tool.poetry.dev-dependencies]
black = "^20.8b0"
flake8 = "^4.0.1"
isort = "^5.0"
pytest = "^6.2.5"
ipykernel = ">=5.0"
ipython = "^7.10"
ipdb = "^0.10.0"
mypy = "^0.931"
python-dotenv = "^0.19.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
line-length = 88
target-version = ['py38']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
