# environment variable names
BASE_URL = "CASTOR_QLIK_BASE_URL"
API_KEY = "CASTOR_QLIK_API_KEY"

# API settings
API_BASE_PATH = "api/v1/"

# requests retry settings
RETRY_COUNTS = 3
RETRY_STATUSES = [404, 500, 502, 503, 504]
RETRY_BACKOFF_FACTOR = 0.5

_RESPONSE_BASE_EXPECTED_MSG = "Expecting HTTP response to be a {type}"
RESPONSE_DICT_EXPECTED_MSG = _RESPONSE_BASE_EXPECTED_MSG.format(type="dict")
RESPONSE_LIST_EXPECTED_MSG = _RESPONSE_BASE_EXPECTED_MSG.format(type="list")
