
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T10:09:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aae7cf920b4490d2017e3b9dbaa181cb521686c7",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
