
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T16:19:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3bbb5ea6f5afbbda854ce09d85875e31b6e7d93",
 "version": "0.44.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
