
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T20:13:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9752260167f819e9b23bb6119e5b5a68b5de0d78",
 "version": "2.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
