
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T13:41:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6aac230d961e7761e0293e013fc536c17f700add",
 "version": "1.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
