[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="pctheory"
version = "0.0.2"
dependencies = [
    "numpy",
    "matplotlib",
    "networkx",
    "pyvis",
]
