[tool.black]
line-length = 88  # Specify the line length
target-version = ['py37']  # Specify your Python version
include = '\.pyi?$'
exclude = '''  # Specify the files/dirs that should be ignored by the black formatter
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
fail_under = 50

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch"
update_changelog_on_bump = true
version = "1.0.0"
version_files = [
    "aqueduct/__init__.py:__version__",
]

[tool.isort]
multi_line_output = 3

[tool.poetry]
name = "sw-aqueduct"
version = "1.1.7"
description = "A Swimlane content delivery system written in Python"
authors = ["MSAdministrator <rickardja@live.com>"]
license = "MIT"
readme = "README.md"
packages = [
  { include = "aqueduct" }
]


[tool.poetry.dependencies]
python = "^3.6.2"
pyyaml = "^6.0"
fire = "^0.4.0"
attrs = "^21.4.0"
pydantic = "^1.9.1"
pendulum = "^2.1.2"
packaging = "^21"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "7.0.1"
coverage = "6.2"
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
bandit = "1.7.1"
safety = "^1.10.3"
mkdocs-material = "^8.2.0"
mkdocstrings = "0.16.2"
mike = "^1.1.2"
Pygments = ">=2.12,<2.13"
swimlane = "^10.4.0"
pre-commit = "<=2.17.0"
colorama = "^0.4.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
