[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digolds-cn"
version = "1.0.0"
description = "Visit digolds's home page"
readme = "README.md"
authors = [{ name = "digolds.cn", email = "founders@digolds.cn" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["digolds", "digolds.cn"]
dependencies = ["requests >= 2.24.0"]
requires-python = ">=3.7"

[project.optional-dependencies]
build = ["build", "twine"]
dev   = ["pytest"]

[project.scripts]
digolds = "visitor.__main__:main"

[project.urls]
repository    = "https://github.com/digolds/visitor"
documentation = "https://www.digolds.cn/article/001657582121249b1a45f4cf3b7468483136c61ac159786000"