[project]
name = "sol-metaplex-utils"
version = "0.4.0"
authors = [
  { name="sol_metaplex_fan", email="sol_metaplex_fan@proton.me" },
]
description = "sol metaplex utils"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"