[build-system]
requires = ["setuptools>=61.0.0", "wheel", "aiohttp"]
build-backend = "setuptools.build_meta"

[project]
name = "aioliqpay"
version = "1.0.0"
description = "Asyncio LiqPay SDK for Python"
readme = "README.md"
authors = [{ name = "toxazhl", email = "zhltoxa@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
keywords = ["aioliqpay", "liqpay", "asyncio", "sdk"]
dependencies = [
    "aiohttp",
]
requires-python = ">=3.6"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/toxazhl/aioliqpay"
