[project]
name = "appservice-deployer"
version = "v0.0.5"
description = "Azure App Service file deployer"
authors = [
    { name = "Fabio Felici", email = "fabio.felici96c@gmail.com" },
]
dependencies = []
requires-python = ">=3.8"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/rhslack/appservice-deployer"
"Bug Tracker" = "https://github.com/rhslack/appservice-deployer/issues"

[tool.pdm]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"
