
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:15:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2d06dd03725aee8a237c05c126b50aa5aef2846",
 "version": "0.7.1.post.dev684"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
