
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T11:50:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6daa58a8526cd3ef7f4b8e30fc80cd13280d604",
 "version": "2686"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
