[project]
name = "halmoney"
version = "1.3.5"
authors = [
  { name="s.j.park", email="sjpkorea@yahoo.com" },
]
description = "office helper"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Homepage" = "https://pypi.org/manage/project/halmoney"
