
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T03:21:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "11a0d9f65aee93f0636beccabb37a8fd280e8a22",
 "version": "1.17.0.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
