
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T18:03:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "69edf18dcbf059effe2428a19f11868b64572f82",
 "version": "0.23a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
