[tool.poetry]
name = "quantitizer"
version = "1.0.0"
description = "This package allows to quantitize matrix to compress different ML models."
authors = ["CapBlood <stalker.anonim@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
gensim = "^4.2.0"
numpy = "^1.23.0"
"mega.py" = "^1.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
