[tool.poetry]
name = "disnakedb"
version = "0.1.3"
description = "Easy and fast db for python users"
authors = ["Hawchik"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
