
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T11:58:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ef90345ae71b2fba4d047f054ad59cdc2ed4d5c",
 "version": "0.7.1.post.dev680"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
