
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T16:31:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5f4e1289933b8f5803ffed1a8f08f73caaf0ef2",
 "version": "0.44.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
