
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T20:33:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "337221bcf14cc532dd617e94daebdfd589c9b1ee",
 "version": "3.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
