[tool.poetry]
name = "soundscapy"
version = "0.3.0"
description = "A python library for analysing and visualising soundscape assessments."
authors = ["Andrew Mitchell <mitchellacoustics15@gmail.com>"]
license = "BSD-3-Clause license"

[tool.poetry.dependencies]
python = "^3.10"
seaborn = "^0.11.2"
pyjanitor = "^0.23.1"
pandas-flavor = "^0.3.0"
jupyter = "^1.0.0"
matplotlib = "^3.5.2"
pandas = "^1.4.3"
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
