
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-10T12:43:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1fef51df61a4ede56519f50d97fa1c07720b609",
 "version": "2.7.5.dev20220711"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
