[tool.poetry]
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Datalake Framework"
documentation = "https://docs.equancy.cloud/datalake-framework/latest/index.html"
license = "MIT"
name = "datalake-framework"
packages = [
  {include = "datalake"},
]
readme = "README.md"
repository = "https://github.com/equancy/datalake-framework"
version = "1.0.4"

[tool.poetry.dependencies]
Babel = "^2.10.1"
azure-eventhub = "^5.9.0"
azure-identity = "^1.10.0"
azure-keyvault-secrets = "^4.4.0"
azure-storage-blob = "^12.12.0"
boto3 = "^1.23.3"
google-cloud-monitoring = "^2.9.1"
google-cloud-pubsub = "^2.12.1"
google-cloud-secret-manager = "^2.10.0"
google-cloud-storage = "^2.3.0"
influxdb-client = "^1.28.0"
pandas = {version = "^1.4.2", optional = true}
pendulum = "^2.1.2"
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
black = "^22.3.0"
coverage = "^6.3.3"
flake9 = "^3.8.3"
pytest = "^6.2.5"

[tool.poetry.extras]
all = ["pandas"]
pandas = ["pandas"]

[tool.black]
line-length = 125
target-version = ["py38"]

[tool.coverage.report]
omit = ["tests/*"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = "E501,W503"

[tool.pytest.ini_options]
addopts = "-ra -v --no-header"
filterwarnings = [
  # see https://github.com/googleapis/python-api-common-protos/issues/23
  "ignore:Call to deprecated create function FieldDescriptor",
  "ignore:Call to deprecated create function Descriptor",
  "ignore:Call to deprecated create function EnumDescriptor",
  "ignore:Call to deprecated create function EnumValueDescriptor",
  "ignore:Call to deprecated create function FileDescriptor",
  "ignore:Call to deprecated create function OneofDescriptor",
  "ignore:Call to deprecated create function ServiceDescriptor",
  "ignore:Call to deprecated create function MethodDescriptor",
]
markers = [
  "providers: marks tests requiring cloud providers",
]
minversion = "6.0"
testpaths = ["tests"]
