[tool.poetry]
name = "audiocodes-exporter"
version = "0.1.0"
description = ""
authors = ["Matthew Neirynck <matthew.neirynck@telsmart.eu>"]

[tool.poetry.dependencies]
python = "^3.10"
prometheus-client = "^0.14.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
