[tool.poetry]
name = "stython"
version = "0.1.17"
description = ""
authors = ["Arun Kapila <starshootercity@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
numpy = "^1.22.2"
replit = "^3.2.4"
requests = "^2.28.0"
my-pip-package = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"