[tool.poetry]
name = "devind_helpers"
version = "1.0.1"
description = "Devind helpers."
authors = ["Victor <lyferov@yandex.ru>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/devind-team/devind-django-helpers"
repository = "https://github.com/devind-team/devind-django-helpers"
keywords = ["django", "helpers"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django"
]


[tool.poetry.dependencies]
python = "^3.9"
redis = "^4.3.4"
Django = "^4.0.2"
inflection = "^0.5.1"
flatten-dict = "^0.4.2"
openpyxl = "^3.0.10"
graphql-core = "^3.2.1"
strawberry-django-plus = "^1.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "devind_helpers/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"