[tool.poetry]
name = "lazytracker"
version = "0.2.0"
description = "Caching of functions with respect to code changes and disk-file changes"
authors = ["Michal Pogoda <michal.pogoda@bards.ai>"]
license = "Apache 2.0"
homepage = "https://github.com/mipo57/lazytracker"
repository = "https://github.com/mipo57/lazytracker"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
dill = "^0.3.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
ipykernel = "^6.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
