
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T13:00:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6886ca33c4b284c94b4d6fbc8b73ceda3904cd5e",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
