
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T21:01:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8a22138891e2b5d4f3662ef207ed6ce56dc00d8",
 "version": "0.2.12.post0.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
