[tool.poetry]
name = "hyperfocus"
version = "0.2.1"
description = "Minimalist task manager."
authors = ["u8slvn <u8slvn@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/u8slvn/hyperfocus"
homepage = "https://github.com/u8slvn/hyperfocus"
keywords = [
    "cli",
    "todo",
    "todolist",
    "todo-list",
    "task-list",
    "productivity",
]
include = [
    "LICENSE",
    "CHANGELOG.md",
    "README.md",
]

[tool.poetry.urls]
"Changelog" = "https://github.com/u8slvn/hyperfocus/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.14.8"
tabulate = "^0.8.9"
click = "^8.1.3"
pyperclip = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
mypy = "^0.931"
freezegun = "^1.1.0"
types-tabulate = "^0.8.5"
pre-commit = "^2.19.0"
coverage = {extras = ["toml"], version = "^6.4.1"}

[tool.poetry.scripts]
hyf = "hyperfocus.cli:hyf"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
combine_as_imports = true
lines_after_imports = 2
src_paths = ["hyperfocus", "tests"]

[[tool.mypy.overrides]]
module=["peewee", "pyperclip"]
warn_unused_ignores = false
ignore_missing_imports = true
