[tool.poetry]
name = "high-order-layers-torch"
version = "1.1.16"
description = "High order layers in pytorch"
authors = ["jloverich <john.loverich@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
torch = "*"
pytorch-lightning = "*"
torchmetrics = "^0.6.1"
lightning-bolts = "^0.5.0"

[tool.poetry.dev-dependencies]
pbr = "*"
hydra-core = "*"
matplotlib = "*"
torchvision = "*"
pytest = "*"
torch-optimizer = "^0.3.0"
torchmetrics = "^0.6.0"
coverage = "^6.3.3"
hydra-nevergrad-sweeper = "^1.2.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
