
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-05T23:45:00-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "04b67e2db5c2e369ad3aa4261f1caa13334bcb9d",
 "version": "v1.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
