
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T04:24:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3eb72be7655104ca709043034babed66b89c9f0b",
 "version": "1.17.0.post.dev23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
