[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pippy_ls"
version = "1.0.4"
description = "An open-source python package"
readme = "README.md"
authors = [{ name = "Pippy Long Stockings", email = "zpprado@email.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["python", "package"]
dependencies = [
    "feedparser >= 5.2.0",
    "html2text",
    "tomli>=2.0.1",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/pradoz/pippy-ls"

[project.scripts]
pippy_ls = "pippy_ls.__main__:main"

[tool.bumpver]
current_version = "1.0.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"src/pippy_ls/__init__.py" = ["{version}"]
