[package]
name = "snapatac2"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
#snapatac2-core = { git = "https://github.com/kaizhang/SnapATAC2.git", rev = "2f92a398d64b825132301cb7712d987969e156a9" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "77f6f6835865c807103be2af2553f0e953f9417b" }
pyanndata = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "77f6f6835865c807103be2af2553f0e953f9417b" }
snapatac2-core = { path = "../snapatac2-core" }
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
#pyanndata = { path = "../../anndata-rs/pyanndata" }
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "75554f7596f51a654711236b385008043efc50bf" }
itertools = "0.8"
flate2 = "1.0"
hdf5 = "0.8.1"
rayon = "1.5.1"
linreg = "0.2.0"
numpy = "0.16"
nalgebra-sparse = "0.6.0"
ndarray = "0.15.4"
linfa = "0.5"
linfa-clustering = "0.5"
rand_isaac = "0.3.0"
rand_core = "0.6"
hora = "0.1.1"
polars = { version = "0.20.0", features = ["ndarray", "dtype-categorical"] }
tempfile = "3.3.0"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = {version = "0.5", features = ["disable_initial_exec_tls"]}

[dependencies.pyo3]
version = "0.16.2"
features = ["extension-module"]

[lib]
name = "_snapatac2"
crate-type = ["cdylib"]
