# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"suspect": "10_noise.ipynb"}

modules = ["noise.py"]

doc_url = "https://Tre-Xanh.github.io/lapros/"

git_url = "https://github.com/Tre-Xanh/lapros/tree/master/"

def custom_doc_links(name): return None
