[tool.poetry]
name = "nisa-di"
version = "0.1.3"
description = "nisa dependencies injection pure python"
authors = ["vaziria <manorder123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
