[tool.poetry]
name = "python-lambda-builder"
version = "0.1.1"
description = "A CLI application for building lambda python functions and dependencies"
readme = "README.md"
authors = ["Damilola Adeyemi <adeyemidamilola3@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.5.0"}
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
mypy = "^0.961"
flake8 = "^4.0.1"
types-toml = "^0.10.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.json
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[tool.poetry.scripts]
python_lambda_builder = "python_lambda_builder.build:run"
