[tool.poetry]
name = "omoidasu"
version = "0.2.1"
description = "CLI for Omoidasu."
authors = ["0djentd"]

[tool.poetry.scripts]
omoidasu = "omoidasu.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
click = "^8.1.3"
appdirs = "^1.4.4"
rich = "^12.4.4"
pydantic = "^1.9.1"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
