
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T11:20:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74fec3605bdc9e422c1ad3f517a0e333fde7a603",
 "version": "1.17.0.post.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
