[tool.poetry]
name = "rest-framework-money-field"
version = "2.0.0"
description = "A DRF serializer for monetary values."
authors = ["Rauli Laine <rauli.laine@treet.fi>"]
license = "MIT"
readme = "README.md"
exclude = ["rest_framework_money_field/tests"]

[tool.poetry.dependencies]
python = "^3.8"
djangorestframework = ">3.7.0,<4.0.0"
py-moneyed = ">=2.0,<3.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
addopts = "--cov=rest_framework_money_field --cov-report=term-missing"
testpaths = ["rest_framework_money_field"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
