
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T03:25:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f532e38a0aa7c5196146110aada9d7dacea7651",
 "version": "1.17.0.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
