[tool.poetry]
name = "aliby-baby"
version = "0.1.13"
description = "Birth Annotator for Budding Yeast"
authors = ["Julian Pietsch <jpietsch@ed.ac.uk>", "Alán Muñoz <amuoz@ed.ac.uk>"]
license = "MIT"
packages = [
    { include = "baby" },
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1,<3.11"
numpy = "1.21.6" # Pinning numpy and pandas makes dep resolution much faster
pandas = "1.3.3"
tqdm = "^4.62.3"
matplotlib = "^3.5.1"
scikit-image = ">=0.17.1, <=0.19.0"
scikit-learn = "0.22.2.post1"
ray = "^1.13.0"
Pillow = "^9.0.0"
imageio = "2.8.0"
tensorflow = ">=2.0.0, <2.9.1"
xgboost = "1.4.2"
tune-sklearn = "^0.4.1"
colorama = "^0.4.4"
keras-tuner = "1.0.1"
protobuf = "<=3.20.1" # For pytest to work

[tool.poetry.dev-dependencies]
black = "^21.12b0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
