[tool.poetry]
name = "yagls"
version = "1.4.0"
description = "Yet Another Github Label Synchroniser"
authors = ["preeded <86511859+preeded@users.noreply.github.com>"]
maintainers = ["preeded <86511859+preeded@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/github-labels/yagls"


[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
