exclude: |
    (?x)^(
        docs/|
        old/|
        .gitignore|
        .setup.py|
        .setup.cfg|
        LICENSE.rst|
        NOTICE.rst|
        CHANGELOG.rst|
        CONTRIBUTING.rst|
        README.rst|
        .pre-commit-config.yaml
    )$
repos:
#Standard hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    #-   id: detect-aws-credentials
    #-   id: detect-private-key
    #-   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: name-tests-test
    #-   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
# Add trailing comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
# Automatic pep8 compliance
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
# Reorder python imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.3.0
    hooks:
    -   id: reorder-python-imports
# Detect dead code
#-   repo: https://github.com/asottile/dead
#    rev: v1.5.0
#    hooks:
#    -   id: dead
# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: remove-tabs
#Black style
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
