[tool.poetry]
name = "aliby-post"
version = "0.1.31"
description = "Post-processing tools for aliby pipeline."
authors = ["Alán Muñoz <amuoz@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "postprocessor" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "1.21.6" # Pinning numpy and pandas makes dep resolution much faster
pandas = "1.3.3"
scipy = ">=1.4.1"
PyYAML = "^6.0"
more-itertools = "^8.12.0"
leidenalg = "^0.8.8"
aliby-agora = "^0.2.30"
pathos = "^0.2.8"
seaborn = "^0.11.2"
scikit-learn = ">=0.22"
gaussianprocessderivatives = "^0.1.2"
p-tqdm = "^1.3.3"
pycatch22 = "^0.4.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
