[tool.poetry]
name = "funtools"
version = "0.1.0"
description = "Useful fun tools"
authors = ["ischaojie <zhuzhezhe95@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
rich = "^12.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
