[tool.poetry]
name = "deci-adk"
version = "1.0.3"
description = "Deci AutoNAC Development Kit"
authors = ["Deci AI <rnd@deci.ai>"]

[[tool.poetry.source]]
name = "codeartifact-prod"
url = "https://deci-packages-487290820248.d.codeartifact.us-east-1.amazonaws.com/pypi/deci-packages/simple"
secondary = true

[[tool.poetry.source]]
name = "codeartifact-dev"
url = "https://deci-packages-307629990626.d.codeartifact.us-east-1.amazonaws.com/pypi/deci-packages/simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
torch = ">=1.9.0"
deci-lab-client = ">=2.15.1"
pickle-mixin = "^1.0.2"

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = {extras = ["jupyter"], version = "^22.3.0"}
flake8 = "^4.0.1"
mypy = "^0.950"
types-setuptools = "^57.4.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
