[tool.poetry]
authors = [
  "Muhammad Arslan <Arslanswl909@gmail.com>",
]

description = "A python based random password generator"
homepage = "https://github.com/Arslan909/pypasswordgen"
keywords = ["password", "generator", "random"]
license = "WTFPL"
name = "pypasswordgen"
readme = "README.md"
version = "1.0.1"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
pypasswordgen = "pypasswordgen:generate_password"
