name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  test:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    environment: CI
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.8"

        runs-on: [ubuntu-latest]

        include:
          - python-version: "3.8"
            runs-on: windows-latest

          - python-version: "3.10"
            runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .[test]

      - name: Run tests
        run: make ci-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          # env_vars: PYTHON,OS
          fail_ci_if_error: true
