# Generated by Django 3.2.5 on 2022-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backup_utils', '0004_auto_20220708_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backup_directories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='django_backup_utils_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='django-backup-utils version'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
