
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T08:12:15+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "6aff6f27e91cc3ac04fa645c258f1c02c1e4e200",
 "version": "0.5.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
