agent_name: error_test
author: fetchai
version: 0.1.0
description: A simple agent to test error raised in skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmdQh43mUtMJSLa9ghvwoZjiAcgU98Rb7c98HCf2t2vBNA
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:QmektTWmXcjThQd8md8nSYgLapR3Gks3n3WEzwAWQFgc4z
contracts: []
protocols: []
skills:
- fetchai/error_test_skill:0.1.0:QmZhWDHmU1VTY6ghwFHvcaCUrFBGg7utTdDkckY4Xiy3fr
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
