[tool.poetry]
authors = ["Francisco Del Roio <francipvb@hotmail.com>"]
description = ""
name = "sqlalchemy-extras"
readme = "README.md"
version = "1.2.0"

[tool.poetry.dependencies]
SQLAlchemy = "^1.4.0"
python = "^3.7"

[tool.poetry.dev-dependencies]
SQLAlchemy = {version = "^1.4.0", extras = ["mypy"]}
autoflake = "^1.4"
bandit = "^1.7.4"
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "^0.950"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
