# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/workspace/project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65olymp/workspace/project.proto\x12\x10\x65olymp.workspace\"\xcb\x01\n\x07Project\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\t\x12\x38\n\nvisibility\x18\x04 \x01(\x0e\x32$.eolymp.workspace.Project.Visibility\x12\x1a\n\x10\x61tlas_problem_id\x18\n \x01(\tH\x00\x12\x0e\n\x06labels\x18\x64 \x03(\t\"%\n\nVisibility\x12\x0b\n\x07PRIVATE\x10\x00\x12\n\n\x06PUBLIC\x10\x01\x42\x08\n\x06targetB;Z9github.com/eolymp/contracts/go/eolymp/workspace;workspaceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.workspace.project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9github.com/eolymp/contracts/go/eolymp/workspace;workspace'
  _PROJECT._serialized_start=53
  _PROJECT._serialized_end=256
  _PROJECT_VISIBILITY._serialized_start=209
  _PROJECT_VISIBILITY._serialized_end=246
# @@protoc_insertion_point(module_scope)
