
[tool.poetry]
name = "qoowa"
version = "0.1.0"
description = ""
packages = [{ include = "qoowa", from = "src" }]
authors = ["Gen Xu <gen@nimble.ai>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
