
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T16:11:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "40867c7fb4e6c40c3689874b17b9c04b2b616b74",
 "version": "2022.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
