[tool.poetry]
name = "aws-iam-login"
version = "0.1.1"
description = "Configures STS credentials using a MFA authenticated session."
authors = ["Joris Conijn <jorisconijn@binx.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
boto3 = "^1.24.11"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.6.0"
pytest-cov = "^3.0.0"
mypy = "^0.961"
radon = "^5.1.0"
xenon = "^0.9.0"
twine = "^4.0.1"

[tool.poetry.scripts]
aws-iam-login = "aws_iam_login:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
