[tool.poetry]
name = "souswift_core"
version = "1.7.2"
description = ""
authors = ["Gustavo Correa <self.gustavocorrea@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
context-handler = "^4.0.0"
SQLAlchemy = "^1.4.29"
aiomysql = "^0.0.22"
pydantic = {extras = ["email"], version = "^1.9.0"}
fastapi = "^0.71.0"
orjson = "^3.6.6"
tzdata = "^2021.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
blue = "^0.7.0"
isort = "^5.10.1"
autoflake = "^1.4"
python-dotenv = "^0.19.2"
pytest-dotenv = "^0.5.2"
pytest-asyncio = "^0.16.0"
pytest-sugar = "^0.9.4"
pytest-cov = "^3.0.0"
coverage = "^6.2"
sqlalchemy2-stubs = "^0.0.2-alpha.19"
aiosqlite = "^0.17.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
