
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T15:36:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c9d5e643e71c252d823aac80cbe3bfc450cdbc8",
 "version": "1.3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
