[tool.poetry]
name = "sqlalchemy2strawberry"
version = "0.0.1"
description = "A simple tool to convert SQLAlchemy models to Strawberry types"
authors = ["bichanna <nobu.bichanna@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bichanna/sqlalchemy2strawberry"
repository = "https://github.com/bichanna/sqlalchemy2strawberry"
keywords = ["convert", "sqlalchemy", "strawberry", "graphql"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.5.1"
SQLAlchemy = "^1.3.16"
strawberry-graphql = "^0.116.4"
pydantic-sqlalchemy = "^0.0.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
