
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T18:12:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dae298f8d77401a36749bd513ab6e2667fe0d1f2",
 "version": "0.2.12.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
