channels:
- conda-forge
dependencies:
- fsspec
- make
- mypy
- netcdf4
- nomkl
- numpy == 1.22.0
- pytest
- pytest-cov
- rasterio == 1.2.4
- rioxarray
- shapely
- types-setuptools
- xarray >= 0.22.2
- xmlschema
- zarr
