[project]
name = "groll"
version = "0.0.2"

requires-python = ">=3.10"
dependencies = ["click >= 8.1.3"]

[project.scripts]
groll = "groll.groll:cli"

[project.urls]
"Homepage" = "https://github.com/Krognak/groll"
"Bug Tracker" = "https://github.com/Krognak/groll/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
