[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "testspatialcdr"
version = "0.0.2"
authors = [
  { name="Ashish_Swain", email="swain.3@iitj.ac.in" },
]
maintainers = [
  {name = "Shreshth Pal", email = "shreshthpal@outlook.com"}
]
description = "Spacer package for Spatial Transcriptomics"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "pandas>=1.3.5",
  "scikit-learn==1.1.1",
   "numpy>=1.17.3"
]
[project.urls]
"Homepage" = "https://github.com/swainasish/Spectacular"
"Bug Tracker" = "https://github.com/swainasish/Spectacular"





