[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nsii"
version = "0.0.1"
authors = [
  { name="killianfrr", email="killiancharrier8@gmail.com" },
]
description = "Simple CLI for python that uses only native python libraries !"
readme = "README.md"
license = { file="license" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/killianc3/nsii"
"Bug Tracker" = "https://github.com/killianc3/nsii/issues"