
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:12:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa2e3bb74acbfb0c3c459ac9e393829a83c349f0",
 "version": "v1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
