[tool.poetry]
name = "ovretl"
version = "6.0.9"
description = "Python package for Ovrsea ETL"
authors = ["nicolas67 <nicolas@ovrsea.com>", "samybf <samy@ovrsea.com>"]
license="MIT"
readme= "README.md"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.8"
pandas = "^1.0.3"
snapshottest = "^0.5.1"
psycopg2-binary = "^2.8.5"
boto3 = "1.14.48"
botocore = "1.17.48"
time-machine = "2.1.0"
pytz = "^2022.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
