[tool.poetry]
name = "fsai-file-split"
version = "0.1.2"
description = "Split a json or jsonl file into different chunks."
authors = ["Michael Mohamed <michael@foundationstack.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/fsai-dev/fsai-file-split"
repository = "https://github.com/fsai-dev/fsai-file-split"

include = [
    "LICENSE",
]

[tool.poetry.scripts]
file-split = 'fsai_file_split.main:app'

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
loguru = "^0.6.0"
beartype = "^0.10.4"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = ">=5.2"
pandas = "^1.3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''