
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-07-12T09:07:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c09ae77bd85bebec2398af8f0a1cfb2232925c62",
 "version": "2.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
