[tool.poetry]
name = "paf_sapgui_cic"
version = "1.0.16"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
#paf_sapgui = { path = "C://AS_Programme/Development/Projects/sapgui/paf_sapgui/dist/paf_sapgui-1.0.51.tar.gz", develop = false }
paf_sapgui = "^1.0.51"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
