
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-05T20:36:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "25decd7c7b0c4e5b083614b299b3ee14b2c18e11",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
