VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('10')
VERSION_HOUR = int('04')
VERSION_MINUTE = int('41')
MAJOR_VERSION = 0
MINOR_VERSION = 6
PATCH_VERSION = 202207100441
version_date = '2022/07/10 04:41'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
