
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T13:53:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb39a52ef7009ee40ae9954a1193ed041e36120e",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
