
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T14:36:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2022766efef424dc57a6486362b2ca74e69d0a79",
 "version": "2687"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
