
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:33:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bb041910fbea258a0322847ce5558fdca9422b8",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
