
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T12:08:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "db89bb489cd42b73b025b9b9c1f5feacc1ac53a8",
 "version": "2689"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
