[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
ignore-vcs = true
exclude = [
    "sensitive/*",
    ".log"
]



[project]
name = "creativiousUtilities"
version = "1.2.2.dev1"
authors = [{name="Creativious", email="timothy@creativious.net"}]
description = "Experimental and likely to break by update\nIf you are to use this have it require the specific version you know works\nGeneral purpose prebuilt functions for any project that I work on"
readme = "README.md"
username = "__token__"
password = "pypi-AgEIcHlwaS5vcmcCJDRjNDExZWNiLTEwYmUtNDIwYi1hNGRhLWRjMzM4YzQxZmI1OQACRXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJjcmVhdGl2aW91c3V0aWxpdGllcyJdfSwgInZlcnNpb24iOiAxfQAABiAyXfOXb3MyBhJFHU6Qo68RAUhcG8lpETDf2c7p9j97Vw"
requires-python = ">=3.10"
dependancies = ['py-cord>=2.0.0rc1']
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
