
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T23:15:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "878dc753357ef109e8b64aba266a700fe0f028a0",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
