[tool.poetry]
name = "trustfall_py"
version = "0.1.0"
description = "Placeholder package for the Trustfall project: https://github.com/obi1kenobi/trustfall"
authors = ["Predrag Gruevski"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
