[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kafka-job-scheduler"
version = "1.0.0"
authors = [
  { name="Dmitry Grechka", email="dmitry@kashtanka.pet" },
]
description = "A job queue based on Apache Kafka"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"

classifiers=[
        'License :: OSI Approved :: MIT License',  
        'Operating System :: OS Independent',        
        'Programming Language :: Python :: 3',
    ]

[project.urls]
"Homepage" = "https://github.com/LostPetInitiative/kafka-job-scheduler"
"Bug Tracker" = "https://github.com/LostPetInitiative/kafka-job-scheduler"