[tool.poetry]
name = "five18"
version = "0.1.0"
description = "Utilities for dealing with pyproject.toml files"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mharrisb1/five18"
homepage = "https://github.com/mharrisb1/five18"
documentation = "https://github.com/mharrisb1/five18"
authors = ["Michael Harris <mharris@luabase.com>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
tomli = { version = "^2.0.1", python = "<3.11" }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.6.0"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
