
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:06:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "28c6181088f8cc33c7a0df393dffa4e2fa0a28d6",
 "version": "0.306"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
