
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T15:45:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5bfa3e841bc31663c9bbb43dcf87e1915f2947b",
 "version": "2692"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
