[project]
name = "PySuiteCRM"
version = "2022.7.12"
authors = [
  { name="Russell Juma", email="RussellJuma@gmail.com" },
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/RussellJuma/PySuiteCRM"
"Bug Tracker" = "https://github.com/RussellJuma/PySuiteCRM/issues"