[tool.poetry]
name = "libq"
version = "0.7.3"
description = "Simple async and sync queue system"
authors = ["nuxion <nuxion@gmail.com>"]
homepage = "https://github.com/nuxion/libq"
repository = "https://github.com/nuxion/libq"
keywords = ["queue", "redis", "async", "distributed"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
redis = "^4.3.1"
hiredis = "^2.0.0"
pydantic = "^1.9.0"
nanoid = "^2.0.0"
rich = "^12.4.1"
orjson = "^3.6.8"
croniter = "^1.3.5"

[tool.poetry.dev-dependencies]
ipython = "^8.3.0"
pylint = "^2.13.9"
isort = "^5.10.1"
autopep8 = "^1.6.0"
black = "^22.3.0"
sqlalchemy-stubs = "^0.4"
types-redis = "^4.2.3"
pytest = "^7.1.2"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = [ 'py37', 'py38']
include = '\.pyi?$'

[tool.isort]
profile= "black"
