[tool.poetry]
name = "nonebot_plugin_chatrecorder"
version = "0.1.8"
description = "适用于 Nonebot2 的聊天记录插件"
authors = ["meetwq <meetwq@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/MeetWq/nonebot-plugin-chatrecorder"
repository = "https://github.com/MeetWq/nonebot-plugin-chatrecorder"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-beta.1"
nonebot-adapter-onebot = "^2.0.0-beta.1"
sqlmodel = "^0.0.6"
nonebot-plugin-datastore = "^0.3.0"
typing-extensions = ">=3.10.0,<5.0.0"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"
black = {version = "^21.12b0", allow-prereleases = true}
nonebug = "^0.2.1"
pytest-cov = "^3.0.0"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
