
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-07T20:58:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b88ac2895e87b5e1e9b83c092f933f2d41a64c6",
 "version": "0.2.12.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
