[tool.poetry]
name = "soundscapy"
version = "0.3.1"
description = "A python library for analysing and visualising soundscape assessments."
authors = ["Andrew Mitchell <andrew.mitchell.18@ucl.ac.uk>"]
license = "BSD-3-Clause license"
readme = "README.md"
repository = "https://github.com/MitchellAcoustics/Soundscapy"

[tool.poetry.dependencies]
python = "^3.8"
seaborn = "^0.11.2"
pyjanitor = "^0.23.1"
pandas-flavor = "^0.3.0"
jupyter = "^1.0.0"
matplotlib = "^3.5.2"
pandas = "^1.4.3"
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
