[tool.poetry]
name = "find-similar-and-list"
version = "0.1.2"
description = ""
readme = "README.md"
authors = ["0djentd"]

[tool.poetry.scripts]
find-similar-and-list = "find_similar_and_list.cli:main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
