site_name: GreatAI documentation
site_description: GreatAI helps you easily transform your prototype AI code into production-ready software.
site_author: András Schmelczer

repo_url: https://github.com/schmelczer/great-ai
repo_name: schmelczer/great-ai
edit_uri: edit/main/docs/

theme:
  name: "material"
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

watch:
- docs
- mkdocs.yaml

plugins:
  - git-revision-date-localized:
  - mkdocstrings
  - search
  - mkdocs-jupyter:
      include_source: true
      # allow_errors: false
      # execute: false
      # execute_ignore: "my-secret-files/*.ipynb"
      # theme: dark

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Overview: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
  - Notebook page: simple-mag/train.ipynb
