[tool.poetry]
name = "kuromon"
version = "0.2.0"
description = "Convert a list of dict, dataclass, Pydantic or POPO objects into a string represented table"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
homepage = "https://github.com/ninoseki/kuromon"
repository = "https://github.com/ninoseki/kuromon"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version = "^4.12.0", python = "<3.8"}
pydantic = { version = ">=1.6.2,!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0", optional = true }
tabulate = "^0.8.10"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autopep8 = "^1.6.0"
black = "^22.6.0"
dacite = "^1.6.0"
isort = "^5.10.1"
mypy = "^0.961"
pre-commit = "^2.19.0"
pytest = "^6.2.5"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.4"
pyupgrade = "^2.34.0"

[tool.poetry.extras]
pydantic = ["pydantic"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
