
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-10T17:06:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3957362bd530db16b9d8b49df4e5d6ad9a37bc4",
 "version": "2.0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
