[project]
name = "demo_package_python"
version = "0.0.10"
description = "This is a sample package which follows the instructions for publishing a Python package to PyPI."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
dependencies = []
[[project.authors]]
name = "Example"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://gitlab.com/demo-package/demo-package-python"
"Bug Tracker" = "https://github.com/demo-package/demo-package-python/~/issues"
