[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smspool"
version = "0.0.4"
authors = [
  { name="xm0999", email="xo@rith.xyz" },
]
description = "A small API Wrapper for smspool.net"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/xm0999/smspool"
"Bug Tracker" = "https://github.com/xm0999/smspool/issues"