[tool.poetry]
name = "notional"
version = "0.4.2"
description = "A high-level interface for the Notion SDK."
license = "MIT"
authors = ["Jason Heddings <jheddings@gmail.com>"]
repository = "https://github.com/jheddings/notional/"
homepage = "https://jheddings.github.io/notional/"

[tool.poetry.dependencies]
python = "^3.8"
notion-client = "^1.0.0"
pydantic = "^1.9.1"
html5lib = "^1.1"
urllib3 = "^1.26.10"

[tool.poetry.dev-dependencies]
GitPython = "^3"
pre-commit = "^2.19"
pytest = "^7.1"
coverage = "^6.4"
pytest-vcr = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
