# Generated by Django 3.1 on 2021-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
