# pyproject.toml

[build-system]
requires      = ["setuptools>=59.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[options]
package_dir = "src"

[options.packages.find]
where = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["jtv"]

[project]
name = "jtv"
version = "1.74.0"
description = "Command line utility for visualising JSON and YAML schemas as text trees"
readme = "README.md"
authors = [{ name = "Astrocyte Medical LTD", email = "info@astrocyte-medical.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["json", "tree", "viewer", "cli"]
dependencies = [
    "click",
    "PyYAML>5.1",
    "colr==0.9.1",
    "asciitree",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/astrocyte-medical/jtv"

[project.scripts]
jtv = "jtv.__init__:main"

[console.scripts]
jtv = "jtv:main"

[tool.bumpver]
current_version = "1.74.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"setup.py" = ["version = '{version}'"]
"src/jtv/__init__.py" = ["__version__ = '{version}'"]
"README.md" = [
    "Version-{version}",
    "jtv=={version}"
]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"src/jtv/template.py" = ["version = '{version}'"]
"setup.cfg" = ["version = {version}"]