
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T20:37:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "baa1dc7605fd0f8fdae7de7698b6be6be84f5248",
 "version": "0.2.12.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
