
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T11:41:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "93a9f79b452a03eb8ff464d77e459593f1b89aac",
 "version": "v1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
