[tool.poetry]
name = "markdown-pydantic"
version = "0.1.0"
description = ""
authors = ["Piotr Katolik <katolus@ventress.org>"]
license = "None"

[tool.poetry.dependencies]
python = "^3.10"
Markdown = "^3.3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
