
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-11T11:47:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdbeec4326ecfb147ade906724c6d7c518db5713",
 "version": "1.0.8rc15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
