[tool.poetry]
name = "fluxpoint"
version = "0.1.2"
description = "A library for making interaction with the Fluxpoint API easy."
authors = ["kunosyn <kunosyn@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"