
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T13:23:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ef579a72c6d9e4f1309ae4ed46919a145c6f4f3",
 "version": "v0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
