[package]
name = "poker-log-parser"
version = "0.1.3"
edition = "2021"
autobenches = false
exclude = [
    "/tests/data/rename.py",
    "/tests/data/OnGame",
    "/tests/data/Pluribus",
    "/tests/data/PokerStars",
    "/tests/data/PokerStarsObf",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "poker_log_parser"
crate-type = ["cdylib", "rlib"]
test = true
doctest = false
bench = true
harness = true

[[bin]]
name = "pklpc"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
rayon = "1.5"
memchr = "2"
pyo3 = { version = "0.16.5", features = ["extension-module"] }

# Benchmarking
[dev-dependencies]
criterion = "0.3"

[profile.release]
debug = 1

[[bench]]
name = "bench_simd"
path = "benches/bench_simd.rs"
harness = false

[[bench]]
name = "bench_parse"
path = "benches/bench_parse.rs"
harness = false
