
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-08T12:08:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "49fdd47303823d3054a369a9ffcbd1411fb5c08b",
 "version": "v2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
