
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-09T16:50:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "744931db3a10357186932d77008ad82ad4341264",
 "version": "3.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
