################################################################################
# Configuration des source (volumes) acessibles par les machines
################################################################################
# Liste des noms de source a desactiver
disabled_sources: []
sources:
  # Montage des verifiers du noyeau sur les machines (obligatoire)
  devopstestor_verifiers:
    accessor_type: DirlinkSourceAccessor
    readonly: True
    path:
      local: "$(this::lib_path)/testconf/verifiers"
      machine: /srv/verifiers/generic
  # Montage des verifiers utilisateur sur les machines
  client_verifiers:
    accessor_type: DirlinkSourceAccessor
    readonly: True
    path:
      local: "$(this::client_path)/testconf/verifiers"
      machine: /srv/verifiers/custom
  # Montage de la lib devopstestor vers la machine
  devopstestor_lib:
    accessor_type: DirlinkSourceAccessor
    readonly: True
    path:
      local: "$(this::lib_path)"
      machine: /usr/local/lib/python3.9/dist-packages/devopstestor
