[tool.poetry]
name = "nxpydocs"
version = "0.1.4"
description = "Automated Business Ready Documents from the NX-OS Guestshell"
packages = [{ include = "nxpydocs", from = "src"}]
readme = "README.md"
authors = ["John Capobianco <ptcapo@gmail.com>"]

[tool.poetry.scripts]
nxpydocs = 'nxpydocs.script:run'

[tool.poetry.dependencies]
python = "^3.8"
rich-click = "^1.5.1"
rich = "^12.4.4"
gTTS = "^2.2.4"
PyYAML = "^6.0"
Jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
