[build-system]
requires = ["flit_core >=3.5,<4"]
build-backend = "flit_core.buildapi"

[project]
name= 'tendrils'
authors = [{name = "Emir Karamehmetoglu", email = "emirkmo@github.com"}]
dynamic = ["version", "description"]
classifiers=["Programming Language :: Python :: 3",
                 "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
                 "Operating System :: OS Independent",
                 "Topic :: Scientific/Engineering :: Astronomy"]
requires-python = '>=3.10'
readme = "README.md"
license = {file = "LICENSE.rst"}
dependencies = [
    "requests",
    "astropy>=2.3.1",
    "numpy>=1.19.1",
    "tqdm"]

[project.urls]
Home = "https://github.com/SNFLOWS/tendrils"
