[tool.poetry]
name = "twitter_remove_strangers"
version = "0.1.0"
description = "Removing followers whom you don't follow"
authors = ["51naa"]

[tool.poetry.dependencies]
python = "^3.7"
tweepy = "^4.10.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
twitter_remove_strangers = "twitter_remove_strangers:main"