
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-06T17:13:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7922f7dff3fa22b04d2590d7dc7b05db1ed040f",
 "version": "1.0.2.post.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
