
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-10T14:20:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1df6875d30f4a437c4125b95eb1cc20b7e5d771",
 "version": "1.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
