"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.authentication_details_user import AuthenticationDetailsUser


class TestAuthenticationDetailsUser(unittest.TestCase):
    """AuthenticationDetailsUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationDetailsUser(self):
        """Test AuthenticationDetailsUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticationDetailsUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
