"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.workspace import Workspace
globals()['Workspace'] = Workspace
from kdp_api.model.workspace_list import WorkspaceList


class TestWorkspaceList(unittest.TestCase):
    """WorkspaceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceList(self):
        """Test WorkspaceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
