"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.workspace_management_api import WorkspaceManagementApi  # noqa: E501


class TestWorkspaceManagementApi(unittest.TestCase):
    """WorkspaceManagementApi unit test stubs"""

    def setUp(self):
        self.api = WorkspaceManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_workspace_management_post(self):
        """Test case for workspace_management_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
