"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.authentication_details_authentication_payload import AuthenticationDetailsAuthenticationPayload


class TestAuthenticationDetailsAuthenticationPayload(unittest.TestCase):
    """AuthenticationDetailsAuthenticationPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationDetailsAuthenticationPayload(self):
        """Test AuthenticationDetailsAuthenticationPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticationDetailsAuthenticationPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
