"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.group3 import Group3


class TestGroup3(unittest.TestCase):
    """Group3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroup3(self):
        """Test Group3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Group3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
