"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.ingest_api import IngestApi  # noqa: E501


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self):
        self.api = IngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_ingest_job(self):
        """Test case for create_ingest_job

        Create an Ingest Job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
