"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.data_source_params import DataSourceParams
globals()['DataSourceParams'] = DataSourceParams
from kdp_api.model.ingest_request import IngestRequest


class TestIngestRequest(unittest.TestCase):
    """IngestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIngestRequest(self):
        """Test IngestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IngestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
