"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.query_api import QueryApi  # noqa: E501


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lucene_query(self):
        """Test case for lucene_query

        Query a dataset but run it through the LuceneParser first  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Query a dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
