"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.group_list import GroupList
globals()['GroupList'] = GroupList
from kdp_api.model.group_paginator import GroupPaginator


class TestGroupPaginator(unittest.TestCase):
    """GroupPaginator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupPaginator(self):
        """Test GroupPaginator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupPaginator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
