"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.daily_usage import DailyUsage


class TestDailyUsage(unittest.TestCase):
    """DailyUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDailyUsage(self):
        """Test DailyUsage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DailyUsage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
