# -*- coding: utf-8 -*-
class basic_test_data:

	def __init__(self):
		pass

	def dic_sample(self):
		result = {'column_0': {'timezones': ['Europe/Andorra'], 'code': 'AD', 'continent': 'Europe', 'name': 'Andorra',
		                    'capital': 'Andorra la Vella'},
		       'column_1': {'timezones': ['Asia/Kabul'], 'code': 'AF', 'continent': 'Asia', 'name': 'Afghanistan',
		                    'capital': 'Kabul'},
		       'column_2': {'timezones': ['America/Antigua'], 'code': 'AG', 'continent': 'North America',
		                    'name': 'Antigua and Barbuda', 'capital': "St. John's"},
		       'column_3': {'timezones': ['Europe/Tirane'], 'code': 'AL', 'continent': 'Europe', 'name': 'Albania',
		                    'capital': 'Tirana'},
		       'column_4': {'timezones': ['Asia/Yerevan'], 'code': 'AM', 'continent': 'Asia', 'name': 'Armenia',
		                    'capital': 'Yerevan'},
		       'column_5': {'timezones': ['Africa/Luanda'], 'code': 'AO', 'continent': 'Africa', 'name': 'Angola',
		                    'capital': 'Luanda'},
		       'column_6': {'timezones': ['America/Argentina/Buenos_Aires'], 'code': 'AR', 'continent': 'South America',
		                    'name': 'Argentina', 'capital': 'Buenos Aires'},
		       'column_7': {'timezones': ['Europe/Vienna'], 'code': 'AT', 'continent': 'Europe', 'name': 'Austria',
		                    'capital': 'Vienna'},
		       'column_8': {'timezones': ['Australia/Lord_Howe'], 'code': 'AU', 'continent': 'Oceania',
		                    'name': 'Australia', 'capital': 'Canberra'},
		       'column_9': {'timezones': ['Asia/Baku'], 'code': 'AZ', 'continent': 'Asia', 'name': 'Azerbaijan',
		                    'capital': 'Baku'},
		       'column_10': {'timezones': ['America/Barbados'], 'code': 'BB', 'continent': 'North America',
		                     'name': 'Barbados', 'capital': 'Bridgetown'},
		       'column_11': {'timezones': ['Asia/Dhaka'], 'code': 'BD', 'continent': 'Asia', 'name': 'Bangladesh',
		                     'capital': 'Dhaka'},
		       'column_12': {'timezones': ['Europe/Brussels'], 'code': 'BE', 'continent': 'Europe', 'name': 'Belgium',
		                     'capital': 'Brussels'},
		       'column_13': {'timezones': ['Africa/Ouagadougou'], 'code': 'BF', 'continent': 'Africa',
		                     'name': 'Burkina Faso', 'capital': 'Ouagadougou'},
		       'column_14': {'timezones': ['Europe/Sofia'], 'code': 'BG', 'continent': 'Europe', 'name': 'Bulgaria',
		                     'capital': 'Sofia'},
		       'column_15': {'timezones': ['Asia/Bahrain'], 'code': 'BH', 'continent': 'Asia', 'name': 'Bahrain',
		                     'capital': 'Manama'},
		       'column_16': {'timezones': ['Africa/Bujumbura'], 'code': 'BI', 'continent': 'Africa', 'name': 'Burundi',
		                     'capital': 'Bujumbura'},
		       'column_17': {'timezones': ['Africa/Porto-Novo'], 'code': 'BJ', 'continent': 'Africa', 'name': 'Benin',
		                     'capital': 'Porto-Novo'},
		       'column_18': {'timezones': ['Asia/Brunei'], 'code': 'BN', 'continent': 'Asia',
		                     'name': 'Brunei Darussalam', 'capital': 'Bandar Seri Begawan'},
		       'column_19': {'timezones': ['America/La_Paz'], 'code': 'BO', 'continent': 'South America',
		                     'name': 'Bolivia', 'capital': 'Sucre'},
		       'column_20': {'timezones': ['America/Noronha'], 'code': 'BR', 'continent': 'South America',
		                     'name': 'Brazil', 'capital': 'Brasdlia'},
		       'column_21': {'timezones': ['America/Nassau'], 'code': 'BS', 'continent': 'North America',
		                     'name': 'Bahamas', 'capital': 'Nassau'},
		       'column_22': {'timezones': ['Asia/Thimphu'], 'code': 'BT', 'continent': 'Asia', 'name': 'Bhutan',
		                     'capital': 'Thimphu'},
		       'column_23': {'timezones': ['Africa/Gaborone'], 'code': 'BW', 'continent': 'Africa', 'name': 'Botswana',
		                     'capital': 'Gaborone'},
		       'column_24': {'timezones': ['Europe/Minsk'], 'code': 'BY', 'continent': 'Europe', 'name': 'Belarus',
		                     'capital': 'Minsk'},
		       'column_25': {'timezones': ['America/Belize'], 'code': 'BZ', 'continent': 'North America',
		                     'name': 'Belize', 'capital': 'Belmopan'},
		       'column_26': {'timezones': ['America/St_Johns'], 'code': 'CA', 'continent': 'North America',
		                     'name': 'Canada', 'capital': 'Ottawa'},
		       'column_27': {'timezones': ['Africa/Kinshasa'], 'code': 'CD', 'continent': 'Africa',
		                     'name': 'Democratic Republic of the Congo', 'capital': 'Kinshasa'},
		       'column_28': {'timezones': ['Africa/Brazzaville'], 'code': 'CG', 'continent': 'Africa',
		                     'name': 'Republic of the Congo', 'capital': 'Brazzaville'},
		       'column_29': {'timezones': ['Africa/Abidjan'], 'code': 'CI', 'continent': 'Africa',
		                     'name': "Cte d'Ivoire", 'capital': 'Yamoussoukro'},
		       'column_30': {'timezones': ['America/Santiago'], 'code': 'CL', 'continent': 'South America',
		                     'name': 'Chile', 'capital': 'Santiago'},
		       'column_31': {'timezones': ['Africa/Douala'], 'code': 'CM', 'continent': 'Africa', 'name': 'Cameroon',
		                     'capital': 'Yaound'},
		       'column_32': {'timezones': ['Asia/Shanghai'], 'code': 'CN', 'continent': 'Asia',
		                     'name': "People's Republic of China", 'capital': 'Beijing'},
		       'column_33': {'timezones': ['America/Bogota'], 'code': 'CO', 'continent': 'South America',
		                     'name': 'Colombia', 'capital': 'Bogot'},
		       'column_34': {'timezones': ['America/Costa_Rica'], 'code': 'CR', 'continent': 'North America',
		                     'name': 'Costa Rica', 'capital': 'San Jos'},
		       'column_35': {'timezones': ['America/Havana'], 'code': 'CU', 'continent': 'North America',
		                     'name': 'Cuba', 'capital': 'Havana'},
		       'column_36': {'timezones': ['Atlantic/Cape_Verde'], 'code': 'CV', 'continent': 'Africa',
		                     'name': 'Cape Verde', 'capital': 'Praia'},
		       'column_37': {'timezones': ['Asia/Nicosia'], 'code': 'CY', 'continent': 'Asia', 'name': 'Cyprus',
		                     'capital': 'Nicosia'},
		       'column_38': {'timezones': ['Europe/Prague'], 'code': 'CZ', 'continent': 'Europe',
		                     'name': 'Czech Republic', 'capital': 'Prague'},
		       'column_39': {'timezones': ['Europe/Berlin'], 'code': 'DE', 'continent': 'Europe', 'name': 'Germany',
		                     'capital': 'Berlin'},
		       'column_40': {'timezones': ['Africa/Djibouti'], 'code': 'DJ', 'continent': 'Africa', 'name': 'Djibouti',
		                     'capital': 'Djibouti City'},
		       'column_41': {'timezones': ['Europe/Copenhagen'], 'code': 'DK', 'continent': 'Europe', 'name': 'Denmark',
		                     'capital': 'Copenhagen'},
		       'column_42': {'timezones': ['America/Dominica'], 'code': 'DM', 'continent': 'North America',
		                     'name': 'Dominica', 'capital': 'Roseau'},
		       'column_43': {'timezones': ['America/Santo_Domingo'], 'code': 'DO', 'continent': 'North America',
		                     'name': 'Dominican Republic', 'capital': 'Santo Domingo'},
		       'column_44': {'timezones': ['America/Guayaquil'], 'code': 'EC', 'continent': 'South America',
		                     'name': 'Ecuador', 'capital': 'Quito'},
		       'column_45': {'timezones': ['Europe/Tallinn'], 'code': 'EE', 'continent': 'Europe', 'name': 'Estonia',
		                     'capital': 'Tallinn'},
		       'column_46': {'timezones': ['Africa/Cairo'], 'code': 'EG', 'continent': 'Africa', 'name': 'Egypt',
		                     'capital': 'Cairo'},
		       'column_47': {'timezones': ['Africa/Asmera'], 'code': 'ER', 'continent': 'Africa', 'name': 'Eritrea',
		                     'capital': 'Asmara'},
		       'column_48': {'timezones': ['Africa/Addis_Ababa'], 'code': 'ET', 'continent': 'Africa',
		                     'name': 'Ethiopia', 'capital': 'Addis Ababa'},
		       'column_49': {'timezones': ['Europe/Helsinki'], 'code': 'FI', 'continent': 'Europe', 'name': 'Finland',
		                     'capital': 'Helsinki'},
		       'column_50': {'timezones': ['Pacific/Fiji'], 'code': 'FJ', 'continent': 'Oceania', 'name': 'Fiji',
		                     'capital': 'Suva'},
		       'column_51': {'timezones': ['Europe/Paris'], 'code': 'FR', 'continent': 'Europe', 'name': 'France',
		                     'capital': 'Paris'},
		       'column_52': {'timezones': ['Africa/Libreville'], 'code': 'GA', 'continent': 'Africa', 'name': 'Gabon',
		                     'capital': 'Libreville'},
		       'column_53': {'timezones': ['Asia/Tbilisi'], 'code': 'GE', 'continent': 'Asia', 'name': 'Georgia',
		                     'capital': 'Tbilisi'},
		       'column_54': {'timezones': ['Africa/Accra'], 'code': 'GH', 'continent': 'Africa', 'name': 'Ghana',
		                     'capital': 'Accra'},
		       'column_55': {'timezones': ['Africa/Banjul'], 'code': 'GM', 'continent': 'Africa', 'name': 'The Gambia',
		                     'capital': 'Banjul'},
		       'column_56': {'timezones': ['Africa/Conakry'], 'code': 'GN', 'continent': 'Africa', 'name': 'Guinea',
		                     'capital': 'Conakry'},
		       'column_57': {'timezones': ['Europe/Athens'], 'code': 'GR', 'continent': 'Europe', 'name': 'Greece',
		                     'capital': 'Athens'},
		       'column_58': {'timezones': ['America/Guatemala'], 'code': 'GT', 'continent': 'North America',
		                     'name': 'Guatemala', 'capital': 'Guatemala City'},
		       'column_59': {'timezones': ['America/Guatemala'], 'code': 'GT', 'continent': 'North America',
		                     'name': 'Haiti', 'capital': 'Port-au-Prince'},
		       'column_60': {'timezones': ['Africa/Bissau'], 'code': 'GW', 'continent': 'Africa',
		                     'name': 'Guinea-Bissau', 'capital': 'Bissau'},
		       'column_61': {'timezones': ['America/Guyana'], 'code': 'GY', 'continent': 'South America',
		                     'name': 'Guyana', 'capital': 'Georgetown'},
		       'column_62': {'timezones': ['America/Tegucigalpa'], 'code': 'HN', 'continent': 'North America',
		                     'name': 'Honduras', 'capital': 'Tegucigalpa'},
		       'column_63': {'timezones': ['Europe/Budapest'], 'code': 'HU', 'continent': 'Europe', 'name': 'Hungary',
		                     'capital': 'Budapest'},
		       'column_64': {'timezones': ['Asia/Jakarta'], 'code': 'ID', 'continent': 'Asia', 'name': 'Indonesia',
		                     'capital': 'Jakarta'},
		       'column_65': {'timezones': ['Europe/Dublin'], 'code': 'IE', 'continent': 'Europe',
		                     'name': 'Republic of Ireland', 'capital': 'Dublin'},
		       'column_66': {'timezones': ['Asia/Jerusalem'], 'code': 'IL', 'continent': 'Asia', 'name': 'Israel',
		                     'capital': 'Jerusalem'},
		       'column_67': {'timezones': ['Asia/Calcutta'], 'code': 'IN', 'continent': 'Asia', 'name': 'India',
		                     'capital': 'New Delhi'},
		       'column_68': {'timezones': ['Asia/Baghdad'], 'code': 'IQ', 'continent': 'Asia', 'name': 'Iraq',
		                     'capital': 'Baghdad'},
		       'column_69': {'timezones': ['Asia/Tehran'], 'code': 'IR', 'continent': 'Asia', 'name': 'Iran',
		                     'capital': 'Tehran'},
		       'column_70': {'timezones': ['Atlantic/Reykjavik'], 'code': 'IS', 'continent': 'Europe',
		                     'name': 'Iceland', 'capital': 'Reykjav'},
		       'column_71': {'timezones': ['Europe/Rome'], 'code': 'IT', 'continent': 'Europe', 'name': 'Italy',
		                     'capital': 'Rome'},
		       'column_72': {'timezones': ['America/Jamaica'], 'code': 'JM', 'continent': 'North America',
		                     'name': 'Jamaica', 'capital': 'Kingston'},
		       'column_73': {'timezones': ['Asia/Amman'], 'code': 'JO', 'continent': 'Asia', 'name': 'Jordan',
		                     'capital': 'Amman'},
		       'column_74': {'timezones': ['Asia/Tokyo'], 'code': 'JP', 'continent': 'Asia', 'name': 'Japan',
		                     'capital': 'Tokyo'},
		       'column_75': {'timezones': ['Africa/Nairobi'], 'code': 'KE', 'continent': 'Africa', 'name': 'Kenya',
		                     'capital': 'Nairobi'},
		       'column_76': {'timezones': ['Asia/Bishkek'], 'code': 'KG', 'continent': 'Asia', 'name': 'Kyrgyzstan',
		                     'capital': 'Bishkek'},
		       'column_77': {'timezones': ['Pacific/Tarawa'], 'code': 'KI', 'continent': 'Oceania', 'name': 'Kiribati',
		                     'capital': 'Tarawa'},
		       'column_78': {'timezones': ['Asia/Pyongyang'], 'code': 'KP', 'continent': 'Asia', 'name': 'North Korea',
		                     'capital': 'Pyongyang'},
		       'column_79': {'timezones': ['Asia/Seoul'], 'code': 'KR', 'continent': 'Asia', 'name': 'South Korea',
		                     'capital': 'Seoul'},
		       'column_80': {'timezones': ['Asia/Kuwait'], 'code': 'KW', 'continent': 'Asia', 'name': 'Kuwait',
		                     'capital': 'Kuwait City'},
		       'column_81': {'timezones': ['Asia/Beirut'], 'code': 'LB', 'continent': 'Asia', 'name': 'Lebanon',
		                     'capital': 'Beirut'},
		       'column_82': {'timezones': ['Europe/Vaduz'], 'code': 'LI', 'continent': 'Europe',
		                     'name': 'Liechtenstein', 'capital': 'Vaduz'},
		       'column_83': {'timezones': ['Africa/Monrovia'], 'code': 'LR', 'continent': 'Africa', 'name': 'Liberia',
		                     'capital': 'Monrovia'},
		       'column_84': {'timezones': ['Africa/Maseru'], 'code': 'LS', 'continent': 'Africa', 'name': 'Lesotho',
		                     'capital': 'Maseru'},
		       'column_85': {'timezones': ['Europe/Vilnius'], 'code': 'LT', 'continent': 'Europe', 'name': 'Lithuania',
		                     'capital': 'Vilnius'},
		       'column_86': {'timezones': ['Europe/Luxembourg'], 'code': 'LU', 'continent': 'Europe',
		                     'name': 'Luxembourg', 'capital': 'Luxembourg City'},
		       'column_87': {'timezones': ['Europe/Riga'], 'code': 'LV', 'continent': 'Europe', 'name': 'Latvia',
		                     'capital': 'Riga'},
		       'column_88': {'timezones': ['Africa/Tripoli'], 'code': 'LY', 'continent': 'Africa', 'name': 'Libya',
		                     'capital': 'Tripoli'},
		       'column_89': {'timezones': ['Indian/Antananarivo'], 'code': 'MG', 'continent': 'Africa',
		                     'name': 'Madagascar', 'capital': 'Antananarivo'},
		       'column_90': {'timezones': ['Pacific/Majuro'], 'code': 'MH', 'continent': 'Oceania',
		                     'name': 'Marshall Islands', 'capital': 'Majuro'},
		       'column_91': {'timezones': ['Europe/Skopje'], 'code': 'MK', 'continent': 'Europe', 'name': 'Macedonia',
		                     'capital': 'Skopje'},
		       'column_92': {'timezones': ['Africa/Bamako'], 'code': 'ML', 'continent': 'Africa', 'name': 'Mali',
		                     'capital': 'Bamako'},
		       'column_93': {'timezones': ['Asia/Rangoon'], 'code': 'MM', 'continent': 'Asia', 'name': 'Myanmar',
		                     'capital': 'Naypyidaw'},
		       'column_94': {'timezones': ['Asia/Ulaanbaatar'], 'code': 'MN', 'continent': 'Asia', 'name': 'Mongolia',
		                     'capital': 'Ulaanbaatar'},
		       'column_95': {'timezones': ['Africa/Nouakchott'], 'code': 'MR', 'continent': 'Africa',
		                     'name': 'Mauritania', 'capital': 'Nouakchott'},
		       'column_96': {'timezones': ['Europe/Malta'], 'code': 'MT', 'continent': 'Europe', 'name': 'Malta',
		                     'capital': 'Valletta'},
		       'column_97': {'timezones': ['Indian/Mauritius'], 'code': 'MU', 'continent': 'Africa',
		                     'name': 'Mauritius', 'capital': 'Port Louis'},
		       'column_98': {'timezones': ['Indian/Maldives'], 'code': 'MV', 'continent': 'Asia', 'name': 'Maldives',
		                     'capital': 'Mal'},
		       'column_99': {'timezones': ['Africa/Blantyre'], 'code': 'MW', 'continent': 'Africa', 'name': 'Malawi',
		                     'capital': 'Lilongwe'},
		       'column_100': {'timezones': ['America/Mexico_City'], 'code': 'MX', 'continent': 'North America',
		                      'name': 'Mexico', 'capital': 'Mexico City'},
		       'column_101': {'timezones': ['Asia/Kuala_Lumpur'], 'code': 'MY', 'continent': 'Asia', 'name': 'Malaysia',
		                      'capital': 'Kuala Lumpur'},
		       'column_102': {'timezones': ['Africa/Maputo'], 'code': 'MZ', 'continent': 'Africa', 'name': 'Mozambique',
		                      'capital': 'Maputo'},
		       'column_103': {'timezones': ['Africa/Windhoek'], 'code': 'NA', 'continent': 'Africa', 'name': 'Namibia',
		                      'capital': 'Windhoek'},
		       'column_104': {'timezones': ['Africa/Niamey'], 'code': 'NE', 'continent': 'Africa', 'name': 'Niger',
		                      'capital': 'Niamey'},
		       'column_105': {'timezones': ['Africa/Lagos'], 'code': 'NG', 'continent': 'Africa', 'name': 'Nigeria',
		                      'capital': 'Abuja'},
		       'column_106': {'timezones': ['America/Managua'], 'code': 'NI', 'continent': 'North America',
		                      'name': 'Nicaragua', 'capital': 'Managua'},
		       'column_107': {'timezones': ['Europe/Amsterdam'], 'code': 'NL', 'continent': 'Europe',
		                      'name': 'Kingdom of the Netherlands', 'capital': 'Amsterdam'},
		       'column_108': {'timezones': ['Europe/Oslo'], 'code': 'NO', 'continent': 'Europe', 'name': 'Norway',
		                      'capital': 'Oslo'},
		       'column_109': {'timezones': ['Asia/Katmandu'], 'code': 'NP', 'continent': 'Asia', 'name': 'Nepal',
		                      'capital': 'Kathmandu'},
		       'column_110': {'timezones': ['Pacific/Nauru'], 'code': 'NR', 'continent': 'Oceania', 'name': 'Nauru',
		                      'capital': 'Yaren'},
		       'column_111': {'timezones': ['Pacific/Auckland'], 'code': 'NZ', 'continent': 'Oceania',
		                      'name': 'New Zealand', 'capital': 'Wellington'},
		       'column_112': {'timezones': ['Asia/Muscat'], 'code': 'OM', 'continent': 'Asia', 'name': 'Oman',
		                      'capital': 'Muscat'},
		       'column_113': {'timezones': ['America/Panama'], 'code': 'PA', 'continent': 'North America',
		                      'name': 'Panama', 'capital': 'Panama City'},
		       'column_114': {'timezones': ['America/Lima'], 'code': 'PE', 'continent': 'South America', 'name': 'Peru',
		                      'capital': 'Lima'},
		       'column_115': {'timezones': ['Pacific/Port_Moresby'], 'code': 'PG', 'continent': 'Oceania',
		                      'name': 'Papua New Guinea', 'capital': 'Port Moresby'},
		       'column_116': {'timezones': ['Asia/Manila'], 'code': 'PH', 'continent': 'Asia', 'name': 'Philippines',
		                      'capital': 'Manila'},
		       'column_117': {'timezones': ['Asia/Karachi'], 'code': 'PK', 'continent': 'Asia', 'name': 'Pakistan',
		                      'capital': 'Islamabad'},
		       'column_118': {'timezones': ['Europe/Warsaw'], 'code': 'PL', 'continent': 'Europe', 'name': 'Poland',
		                      'capital': 'Warsaw'},
		       'column_119': {'timezones': ['Europe/Lisbon'], 'code': 'PT', 'continent': 'Europe', 'name': 'Portugal',
		                      'capital': 'Lisbon'},
		       'column_120': {'timezones': ['Pacific/Palau'], 'code': 'PW', 'continent': 'Oceania', 'name': 'Palau',
		                      'capital': 'Ngerulmud'},
		       'column_121': {'timezones': ['America/Asuncion'], 'code': 'PY', 'continent': 'South America',
		                      'name': 'Paraguay', 'capital': 'Asuncin'},
		       'column_122': {'timezones': ['Asia/Qatar'], 'code': 'QA', 'continent': 'Asia', 'name': 'Qatar',
		                      'capital': 'Doha'},
		       'column_123': {'timezones': ['Europe/Bucharest'], 'code': 'RO', 'continent': 'Europe', 'name': 'Romania',
		                      'capital': 'Bucharest'},
		       'column_124': {'timezones': ['Europe/Kaliningrad'], 'code': 'RU', 'continent': 'Europe',
		                      'name': 'Russia', 'capital': 'Moscow'},
		       'column_125': {'timezones': ['Africa/Kigali'], 'code': 'RW', 'continent': 'Africa', 'name': 'Rwanda',
		                      'capital': 'Kigali'},
		       'column_126': {'timezones': ['Asia/Riyadh'], 'code': 'SA', 'continent': 'Asia', 'name': 'Saudi Arabia',
		                      'capital': 'Riyadh'},
		       'column_127': {'timezones': ['Pacific/Guadalcanal'], 'code': 'SB', 'continent': 'Oceania',
		                      'name': 'Solomon Islands', 'capital': 'Honiara'},
		       'column_128': {'timezones': ['Indian/Mahe'], 'code': 'SC', 'continent': 'Africa', 'name': 'Seychelles',
		                      'capital': 'Victoria'},
		       'column_129': {'timezones': ['Africa/Khartoum'], 'code': 'SD', 'continent': 'Africa', 'name': 'Sudan',
		                      'capital': 'Khartoum'},
		       'column_130': {'timezones': ['Europe/Stockholm'], 'code': 'SE', 'continent': 'Europe', 'name': 'Sweden',
		                      'capital': 'Stockholm'},
		       'column_131': {'timezones': ['Asia/Singapore'], 'code': 'SG', 'continent': 'Asia', 'name': 'Singapore',
		                      'capital': 'Singapore'},
		       'column_132': {'timezones': ['Europe/Ljubljana'], 'code': 'SI', 'continent': 'Europe',
		                      'name': 'Slovenia', 'capital': 'Ljubljana'},
		       'column_133': {'timezones': ['Europe/Bratislava'], 'code': 'SK', 'continent': 'Europe',
		                      'name': 'Slovakia', 'capital': 'Bratislava'},
		       'column_134': {'timezones': ['Africa/Freetown'], 'code': 'SL', 'continent': 'Africa',
		                      'name': 'Sierra Leone', 'capital': 'Freetown'},
		       'column_135': {'timezones': ['Europe/San_Marino'], 'code': 'SM', 'continent': 'Europe',
		                      'name': 'San Marino', 'capital': 'San Marino'},
		       'column_136': {'timezones': ['Africa/Dakar'], 'code': 'SN', 'continent': 'Africa', 'name': 'Senegal',
		                      'capital': 'Dakar'},
		       'column_137': {'timezones': ['Africa/Mogadishu'], 'code': 'SO', 'continent': 'Africa', 'name': 'Somalia',
		                      'capital': 'Mogadishu'},
		       'column_138': {'timezones': ['America/Paramaribo'], 'code': 'SR', 'continent': 'South America',
		                      'name': 'Suriname', 'capital': 'Paramaribo'},
		       'column_139': {'timezones': ['Africa/Sao_Tome'], 'code': 'ST', 'continent': 'Africa',
		                      'name': 'So Tom and Pradncipe', 'capital': 'So Tom'},
		       'column_140': {'timezones': ['Asia/Damascus'], 'code': 'SY', 'continent': 'Asia', 'name': 'Syria',
		                      'capital': 'Damascus'},
		       'column_141': {'timezones': ['Africa/Lome'], 'code': 'TG', 'continent': 'Africa', 'name': 'Togo',
		                      'capital': 'Lom'},
		       'column_142': {'timezones': ['Asia/Bangkok'], 'code': 'TH', 'continent': 'Asia', 'name': 'Thailand',
		                      'capital': 'Bangkok'},
		       'column_143': {'timezones': ['Asia/Dushanbe'], 'code': 'TJ', 'continent': 'Asia', 'name': 'Tajikistan',
		                      'capital': 'Dushanbe'},
		       'column_144': {'timezones': ['Asia/Ashgabat'], 'code': 'TM', 'continent': 'Asia', 'name': 'Turkmenistan',
		                      'capital': 'Ashgabat'},
		       'column_145': {'timezones': ['Africa/Tunis'], 'code': 'TN', 'continent': 'Africa', 'name': 'Tunisia',
		                      'capital': 'Tunis'},
		       'column_146': {'timezones': ['Pacific/Tongatapu'], 'code': 'TO', 'continent': 'Oceania', 'name': 'Tonga',
		                      'capital': 'Nukualofa'},
		       'column_147': {'timezones': ['Europe/Istanbul'], 'code': 'TR', 'continent': 'Asia', 'name': 'Turkey',
		                      'capital': 'Ankara'},
		       'column_148': {'timezones': ['America/Port_of_Spain'], 'code': 'TT', 'continent': 'North America',
		                      'name': 'Trinidad and Tobago', 'capital': 'Port of Spain'},
		       'column_149': {'timezones': ['Pacific/Funafuti'], 'code': 'TV', 'continent': 'Oceania', 'name': 'Tuvalu',
		                      'capital': 'Funafuti'},
		       'column_150': {'timezones': ['Africa/Dar_es_Salaam'], 'code': 'TZ', 'continent': 'Africa',
		                      'name': 'Tanzania', 'capital': 'Dodoma'},
		       'column_151': {'timezones': ['Europe/Kiev'], 'code': 'UA', 'continent': 'Europe', 'name': 'Ukraine',
		                      'capital': 'Kyiv'},
		       'column_152': {'timezones': ['Africa/Kampala'], 'code': 'UG', 'continent': 'Africa', 'name': 'Uganda',
		                      'capital': 'Kampala'},
		       'column_153': {'timezones': ['America/New_York'], 'code': 'US', 'continent': 'North America',
		                      'name': 'United States', 'capital': 'Washington, D.C.'},
		       'column_154': {'timezones': ['America/Montevideo'], 'code': 'UY', 'continent': 'South America',
		                      'name': 'Uruguay', 'capital': 'Montevideo'},
		       'column_155': {'timezones': ['Asia/Samarkand', 'Asia/Tashkent'], 'code': 'UZ', 'continent': 'Asia',
		                      'name': 'Uzbekistan', 'capital': 'Tashkent'},
		       'column_156': {'timezones': ['Europe/Vatican'], 'code': 'VA', 'continent': 'Europe',
		                      'name': 'Vatican City', 'capital': 'Vatican City'},
		       'column_157': {'timezones': ['America/Caracas'], 'code': 'VE', 'continent': 'South America',
		                      'name': 'Venezuela', 'capital': 'Caracas'},
		       'column_158': {'timezones': ['Asia/Saigon'], 'code': 'VN', 'continent': 'Asia', 'name': 'Vietnam',
		                      'capital': 'Hanoi'},
		       'column_159': {'timezones': ['Pacific/Efate'], 'code': 'VU', 'continent': 'Oceania', 'name': 'Vanuatu',
		                      'capital': 'Port Vila'},
		       'column_160': {'timezones': ['Asia/Aden'], 'code': 'YE', 'continent': 'Asia', 'name': 'Yemen',
		                      'capital': "Sana'a"},
		       'column_161': {'timezones': ['Africa/Lusaka'], 'code': 'ZM', 'continent': 'Africa', 'name': 'Zambia',
		                      'capital': 'Lusaka'},
		       'column_162': {'timezones': ['Africa/Harare'], 'code': 'ZW', 'continent': 'Africa', 'name': 'Zimbabwe',
		                      'capital': 'Harare'},
		       'column_163': {'timezones': ['Africa/Algiers'], 'code': 'DZ', 'continent': 'Africa', 'name': 'Algeria',
		                      'capital': 'Algiers'},
		       'column_164': {'timezones': ['Europe/Sarajevo'], 'code': 'BA', 'continent': 'Europe',
		                      'name': 'Bosnia and Herzegovina', 'capital': 'Sarajevo'},
		       'column_165': {'timezones': ['Asia/Phnom_Penh'], 'code': 'KH', 'continent': 'Asia', 'name': 'Cambodia',
		                      'capital': 'Phnom Penh'},
		       'column_166': {'timezones': ['Africa/Bangui'], 'code': 'CF', 'continent': 'Africa',
		                      'name': 'Central African Republic', 'capital': 'Bangui'},
		       'column_167': {'timezones': ['Africa/Ndjamena'], 'code': 'TD', 'continent': 'Africa', 'name': 'Chad',
		                      'capital': "N'Djamena"},
		       'column_168': {'timezones': ['Indian/Comoro'], 'code': 'KM', 'continent': 'Africa', 'name': 'Comoros',
		                      'capital': 'Moroni'},
		       'column_169': {'timezones': ['Europe/Zagreb'], 'code': 'HR', 'continent': 'Europe', 'name': 'Croatia',
		                      'capital': 'Zagreb'},
		       'column_170': {'timezones': ['Asia/Dili'], 'code': 'TL', 'continent': 'Asia', 'name': 'East Timor',
		                      'capital': 'Dili'},
		       'column_171': {'timezones': ['America/El_Salvador'], 'code': 'SV', 'continent': 'North America',
		                      'name': 'El Salvador', 'capital': 'San Salvador'},
		       'column_172': {'timezones': ['Africa/Malabo'], 'code': 'GQ', 'continent': 'Africa',
		                      'name': 'Equatorial Guinea', 'capital': 'Malabo'},
		       'column_173': {'timezones': ['America/Grenada'], 'code': 'GD', 'continent': 'North America',
		                      'name': 'Grenada', 'capital': "St. George's"},
		       'column_174': {'timezones': ['Asia/Almaty'], 'code': 'KZ', 'continent': 'Asia', 'name': 'Kazakhstan',
		                      'capital': 'Astana'},
		       'column_175': {'timezones': ['Asia/Vientiane'], 'code': 'LA', 'continent': 'Asia', 'name': 'Laos',
		                      'capital': 'Vientiane'},
		       'column_176': {'timezones': ['Pacific/Truk'], 'code': 'FM', 'continent': 'Oceania',
		                      'name': 'Federated States of Micronesia', 'capital': 'Palikir'},
		       'column_177': {'timezones': ['Europe/Chisinau'], 'code': 'MD', 'continent': 'Europe', 'name': 'Moldova',
		                      'capital': 'Chiinu'},
		       'column_178': {'timezones': ['Europe/Monaco'], 'code': 'MC', 'continent': 'Europe', 'name': 'Monaco',
		                      'capital': 'Monaco'},
		       'column_179': {'timezones': ['Europe/Podgorica'], 'code': 'ME', 'continent': 'Europe',
		                      'name': 'Montenegro', 'capital': 'Podgorica'},
		       'column_180': {'timezones': ['Africa/Casablanca'], 'code': 'MA', 'continent': 'Africa',
		                      'name': 'Morocco', 'capital': 'Rabat'},
		       'column_181': {'timezones': ['America/St_Kitts'], 'code': 'KN', 'continent': 'North America',
		                      'name': 'Saint Kitts and Nevis', 'capital': 'Basseterre'},
		       'column_182': {'timezones': ['America/St_Lucia'], 'code': 'LC', 'continent': 'North America',
		                      'name': 'Saint Lucia', 'capital': 'Castries'},
		       'column_183': {'timezones': ['America/St_Vincent'], 'code': 'VC', 'continent': 'North America',
		                      'name': 'Saint Vincent and the Grenadines', 'capital': 'Kingstown'},
		       'column_184': {'timezones': ['Pacific/Apia'], 'code': 'WS', 'continent': 'Oceania', 'name': 'Samoa',
		                      'capital': 'Apia'},
		       'column_185': {'timezones': ['Europe/Belgrade'], 'code': 'RS', 'continent': 'Europe', 'name': 'Serbia',
		                      'capital': 'Belgrade'},
		       'column_186': {'timezones': ['Africa/Johannesburg'], 'code': 'ZA', 'continent': 'Africa',
		                      'name': 'South Africa', 'capital': 'Pretoria'},
		       'column_187': {'timezones': ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'], 'code': 'ES',
		                      'continent': 'Europe', 'name': 'Spain', 'capital': 'Madrid'},
		       'column_188': {'timezones': ['Asia/Colombo'], 'code': 'LK', 'continent': 'Asia', 'name': 'Sri Lanka',
		                      'capital': 'Sri Jayewardenepura Kotte'},
		       'column_189': {'timezones': ['Africa/Mbabane'], 'code': 'SZ', 'continent': 'Africa', 'name': 'Swaziland',
		                      'capital': 'Mbabane'},
		       'column_190': {'timezones': ['Europe/Zurich'], 'code': 'CH', 'continent': 'Europe',
		                      'name': 'Switzerland', 'capital': 'Bern'},
		       'column_191': {'timezones': ['Asia/Dubai'], 'code': 'AE', 'continent': 'Asia',
		                      'name': 'United Arab Emirates', 'capital': 'Abu Dhabi'},
		       'column_192': {'timezones': ['Europe/London'], 'code': 'GB', 'continent': 'Europe',
		                      'name': 'United Kingdom', 'capital': 'London'}}
		return result