# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/operations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api import ids_pb2 as api_dot_ids__pb2
from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/entity/operations.proto\x12\x03\x61pi\x1a\rapi/ids.proto\x1a\x17validate/validate.proto\"=\n\rExecutionPlan\x12,\n\noperations\x18\x01 \x03(\x0b\x32\x0e.api.OperationB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\"t\n\tOperation\x12.\n\nsequential\x18\x01 \x01(\x0b\x32\x18.api.SequentialOperationH\x00\x12*\n\x08parallel\x18\x02 \x01(\x0b\x32\x16.api.ParallelOperationH\x00\x42\x0b\n\toperation\"\xc4\x01\n\x13SequentialOperation\x12:\n\x11\x66\x65\x61ture_set_build\x18\x01 \x01(\x0b\x32\x1d.api.FeatureSetBuildOperationH\x00\x12/\n\x0bmodel_train\x18\x02 \x01(\x0b\x32\x18.api.ModelTrainOperationH\x00\x12\x33\n\rdataset_build\x18\x04 \x01(\x0b\x32\x1a.api.DatasetBuildOperationH\x00\x42\x0b\n\toperation\"\xaf\x01\n\x11ParallelOperation\x12\x38\n\x11\x66\x65\x61ture_set_build\x18\x01 \x03(\x0b\x32\x1d.api.FeatureSetBuildOperation\x12-\n\x0bmodel_train\x18\x02 \x03(\x0b\x32\x18.api.ModelTrainOperation\x12\x31\n\rdataset_build\x18\x04 \x03(\x0b\x32\x1a.api.DatasetBuildOperation\"H\n\x18\x46\x65\x61tureSetBuildOperation\x12\x18\n\x10\x66\x65\x61ture_set_name\x18\x01 \x01(\t\x12\x12\n\ndependency\x18\x02 \x03(\t\"X\n\x13ModelTrainOperation\x12-\n\x10model_version_id\x18\x01 \x01(\x0b\x32\x13.api.ModelVersionId\x12\x12\n\ndependency\x18\x02 \x03(\t\"A\n\x15\x44\x61tasetBuildOperation\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x12\n\ndependency\x18\x02 \x03(\tB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_EXECUTIONPLAN = DESCRIPTOR.message_types_by_name['ExecutionPlan']
_OPERATION = DESCRIPTOR.message_types_by_name['Operation']
_SEQUENTIALOPERATION = DESCRIPTOR.message_types_by_name['SequentialOperation']
_PARALLELOPERATION = DESCRIPTOR.message_types_by_name['ParallelOperation']
_FEATURESETBUILDOPERATION = DESCRIPTOR.message_types_by_name['FeatureSetBuildOperation']
_MODELTRAINOPERATION = DESCRIPTOR.message_types_by_name['ModelTrainOperation']
_DATASETBUILDOPERATION = DESCRIPTOR.message_types_by_name['DatasetBuildOperation']
ExecutionPlan = _reflection.GeneratedProtocolMessageType('ExecutionPlan', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONPLAN,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.ExecutionPlan)
  })
_sym_db.RegisterMessage(ExecutionPlan)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.Operation)
  })
_sym_db.RegisterMessage(Operation)

SequentialOperation = _reflection.GeneratedProtocolMessageType('SequentialOperation', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENTIALOPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.SequentialOperation)
  })
_sym_db.RegisterMessage(SequentialOperation)

ParallelOperation = _reflection.GeneratedProtocolMessageType('ParallelOperation', (_message.Message,), {
  'DESCRIPTOR' : _PARALLELOPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.ParallelOperation)
  })
_sym_db.RegisterMessage(ParallelOperation)

FeatureSetBuildOperation = _reflection.GeneratedProtocolMessageType('FeatureSetBuildOperation', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESETBUILDOPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.FeatureSetBuildOperation)
  })
_sym_db.RegisterMessage(FeatureSetBuildOperation)

ModelTrainOperation = _reflection.GeneratedProtocolMessageType('ModelTrainOperation', (_message.Message,), {
  'DESCRIPTOR' : _MODELTRAINOPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.ModelTrainOperation)
  })
_sym_db.RegisterMessage(ModelTrainOperation)

DatasetBuildOperation = _reflection.GeneratedProtocolMessageType('DatasetBuildOperation', (_message.Message,), {
  'DESCRIPTOR' : _DATASETBUILDOPERATION,
  '__module__' : 'api.entity.operations_pb2'
  # @@protoc_insertion_point(class_scope:api.DatasetBuildOperation)
  })
_sym_db.RegisterMessage(DatasetBuildOperation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _EXECUTIONPLAN.fields_by_name['operations']._options = None
  _EXECUTIONPLAN.fields_by_name['operations']._serialized_options = b'\372B\005\222\001\002\010\001'
  _EXECUTIONPLAN._serialized_start=76
  _EXECUTIONPLAN._serialized_end=137
  _OPERATION._serialized_start=139
  _OPERATION._serialized_end=255
  _SEQUENTIALOPERATION._serialized_start=258
  _SEQUENTIALOPERATION._serialized_end=454
  _PARALLELOPERATION._serialized_start=457
  _PARALLELOPERATION._serialized_end=632
  _FEATURESETBUILDOPERATION._serialized_start=634
  _FEATURESETBUILDOPERATION._serialized_end=706
  _MODELTRAINOPERATION._serialized_start=708
  _MODELTRAINOPERATION._serialized_end=796
  _DATASETBUILDOPERATION._serialized_start=798
  _DATASETBUILDOPERATION._serialized_end=863
# @@protoc_insertion_point(module_scope)
