[tool.poetry]
name = "compositry"
version = "0.4.0"
description = "A tiny library inspired by frontend frameworks to experiment with the idea of composable automation scripts reduced to functions."
authors = ["Dense Reptile <80247368+DenseReptile@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["components"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pylint = "^2.14.4"
hypothesis = {extras = ["cli"], version = "^6.49.1"}

[tool.isort]
profile = "black"

[tool.pylint.FORMAT]
max-line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
