
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-10T11:14:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1150afee4df50df040b8b6bcab9f760800f7254",
 "version": "2.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
