[project]
name = "dive-nemo"
version = "0.0.1"
authors = [
	{ name = "Ivo Simonsmeier", email = "simonsmeier@dive-solutions.de" },
]
description = "Dependency Confusion Placeholder"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://www.dive-solutions.de/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
