[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "bungocrypt"
version = "1.0.3"
authors = [
  { name="NikkieDev Software", email="business@nikkiedev.com" },
]
description = "bungocrypt is an encryption library for python. It's secure and key based so it will keep your data safe!"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    ]